import type { CourseLanguage, CourseLesson } from './course-catalog';

export const equipmentCourse: Record<CourseLanguage, CourseLesson> = {
  en: {
    slides: [
      { n: '01', title: 'Only trained, authorized operators may operate', text: 'The employer must ensure operators are trained and evaluated for the equipment and workplace. Before the shift, check brakes, steering, horn, reverse alarm, lights, tires/tracks, guards, seat belt, ROPS, mirrors/cameras, leaks and attachments. Verify the rated capacity and manufacturer instructions. Tag out equipment with a safety defect; never rely on “it worked yesterday.”', ref: '29 CFR 1926.20(b)(4); 1926.602(a), (d); 1910.178(l)' },
      { n: '02', title: 'Wear the seat belt and stay inside the protective zone', text: 'Seat belts are required on covered earthmoving equipment where provided with ROPS or adequate canopy protection; use them every trip. Do not jump from a rolling or overturning machine—remain seated, belt fastened, brace and lean away from impact. No unauthorized riders are permitted on powered industrial trucks, and an authorized rider needs a safe riding place. Never carry a person in a bucket, on forks or on a step.', ref: '29 CFR 1926.602(a)(2), (b)(1), (c)(1)(vii)' },
      { n: '03', title: 'Reverse only with an alarm or a signaler', text: 'Bidirectional machines need an operative horn distinguishable from site noise. Earthmoving or compacting equipment with an obstructed rear view may not reverse unless a reverse alarm is operating and distinguishable from background noise, or an employee signals that it is safe. Stop immediately if visual contact with the signaler is lost. Establish a pedestrian-free operating zone and never assume a camera removes blind spots.', ref: '29 CFR 1926.602(a)(9)' },
      { n: '04', title: 'Park, lower, neutralize, brake and chock', text: 'When parked, set the parking brake. On an incline, set the brake and chock the wheels. Lower blades, buckets, dump bodies and similar equipment or block them securely. Before anyone works under or between raised parts, substantially block or crib them against falling or shifting; place controls in neutral, stop the motor and set brakes unless the task specifically requires otherwise. Hydraulic pressure alone is not support.', ref: '29 CFR 1926.600(a)(3)' },
      { n: '05', title: 'Respect capacity, grades and edge stability', text: 'Use only roadways and grades constructed and maintained for the equipment. Emergency ramps and berms must restrain runaway vehicles. Brakes must stop and hold the fully loaded machine. Rated capacity must be visible on lift trucks and never exceeded; capacity-affecting modifications require written manufacturer approval and updated plates. Keep back from excavations and soft shoulders based on the competent person’s assessment and the equipment’s weight and ground pressure.', ref: '29 CFR 1926.602(a)(3)–(4), (c)(1)(i)–(iii)' },
      { n: '06', title: 'Maintain electrical clearance', text: 'Treat every overhead wire as energized until the owner or utility confirms otherwise and it is visibly grounded. For covered equipment near power lines, keep at least 10 ft (3.1 m) from lines rated 50 kV or below. Above 50 kV, use 10 ft plus 0.4 in for every kV over 50, or twice the insulator length—never less than 10 ft. Use a designated observer when the operator cannot judge clearance reliably.', ref: '29 CFR 1926.600(a)(6)' },
      { n: '07', title: 'Separate people from the machine', text: 'Plan one-way routes, speed controls, crossing points, lighting and exclusion zones. Approach only after eye contact, operator acknowledgement, machine stopped and attachment grounded. Never stand between moving equipment and a fixed object, under a raised load, or in the swing radius. Use barriers and a spotter where visibility is restricted. High-visibility clothing improves detection but does not replace physical separation.', ref: '29 CFR 1926.200; 1926.201; 1926.600; 1926.602' },
      { n: '08', title: 'Stop for defects, lost communication or changed conditions', text: 'The operator controls the machine and must stop for people in the zone, failed alarms, brake or steering faults, unstable ground, overload, leaking fluids, poor visibility or lost signal contact. Supervisors must not pressure an operator to continue. Reinspect after repair, attachment change, impact or relocation. Memory rule: inspect, isolate, communicate, operate—then park and secure.', ref: '29 CFR 1926.20(b); 1926.600; 1926.602' },
    ],
    quiz: [
      { q: 'An earthmover has an obstructed rear view. When may it reverse?', a: ['Whenever the operator sounds the horn', 'Only with an operating distinguishable reverse alarm or an employee signaling that it is safe', 'When no supervisor is present', 'At walking speed without an alarm'], correct: 1 },
      { q: 'What is required when equipment is parked on an incline?', a: ['Parking brake set and wheels chocked', 'Bucket raised for visibility', 'Transmission left in forward gear', 'Engine left running'], correct: 0 },
      { q: 'What is the normal minimum clearance from a power line rated 50 kV or below?', a: ['3 ft', '6 ft', '8 ft', '10 ft (3.1 m)'], correct: 3 },
      { q: 'Who may ride on a powered industrial truck?', a: ['Any worker wearing a hard hat', 'An authorized person provided with a safe riding place', 'Anyone holding the frame', 'Only the signaler standing on the forks'], correct: 1 },
      { q: 'What supports a raised bucket during maintenance?', a: ['Hydraulic pressure', 'A coworker at the controls', 'Substantial blocking or cribbing', 'The parking brake alone'], correct: 2 },
    ],
  },
  ar: {
    slides: [
      { n: '01', title: 'التشغيل للمدرّب والمصرح له فقط', text: 'يضمن صاحب العمل تدريب المشغل وتقييمه على المعدة والموقع. قبل الوردية افحص الفرامل والتوجيه والبوق وإنذار الرجوع والإضاءة والإطارات أو الجنزير والحواجز والحزام وROPS والمرايا والتسربات والملحقات. تحقق من السعة وتعليمات المصنع. ضع بطاقة منع استخدام على أي معدة بها عيب سلامة.', ref: '29 CFR 1926.20(b)(4); 1926.602(a), (d); 1910.178(l)' },
      { n: '02', title: 'اربط الحزام وابقَ داخل منطقة الحماية', text: 'تُستخدم أحزمة المقاعد في معدات تحريك التربة المشمولة والمزودة بـROPS أو مظلة حماية. لا تقفز من آلة تتحرك أو تنقلب؛ ابقَ جالساً والحزام مربوطاً. لا يُسمح بركاب غير مصرح لهم على الشاحنات الصناعية، والراكب المصرح يحتاج مكاناً آمناً. لا تحمل شخصاً في الجرافة أو على الشوك أو الدرج.', ref: '29 CFR 1926.602(a)(2), (b)(1), (c)(1)(vii)' },
      { n: '03', title: 'ارجع للخلف بإنذار أو موجّه', text: 'تحتاج الآلات ثنائية الاتجاه بوقاً عاملاً مميزاً عن ضوضاء الموقع. لا ترجع معدة تحريك أو دمك التربة ذات الرؤية الخلفية المحجوبة إلا مع إنذار رجوع مسموع أو عامل يعطي إشارة بأن الطريق آمن. أوقف فوراً عند فقد التواصل البصري مع الموجّه. اعزل المشاة ولا تعتبر الكاميرا إزالةً للنقاط العمياء.', ref: '29 CFR 1926.602(a)(9)' },
      { n: '04', title: 'عند الوقوف: اخفض، حيّد، افرمل وثبّت', text: 'فعّل فرامل الوقوف، وعلى المنحدر أضف موانع للعجلات. اخفض الشفرات والجرافات وصناديق القلاب أو ثبّتها. قبل العمل تحت جزء مرفوع، استخدم تدعيماً أو حشواً قوياً يمنع السقوط أو الحركة، وضع التحكم على الحياد وأوقف المحرك وفعّل الفرامل إلا إذا تطلب العمل غير ذلك. الضغط الهيدروليكي ليس دعامة.', ref: '29 CFR 1926.600(a)(3)' },
      { n: '05', title: 'احترم السعة والمنحدرات وثبات الحواف', text: 'استخدم طرقاً ومنحدرات مصممة ومصانة للمعدة. يجب أن تضبط منحدرات الطوارئ والسواتر المركبات الهاربة، وأن توقف الفرامل الآلة المحملة بالكامل. تظهر سعة الرافعة الشوكية بوضوح ولا تُتجاوز؛ وأي تعديل يؤثر في السعة يحتاج موافقة خطية من المصنع وتحديث اللوحة. ابتعد عن الحفريات والأكتاف الضعيفة حسب تقييم الشخص المختص.', ref: '29 CFR 1926.602(a)(3)–(4), (c)(1)(i)–(iii)' },
      { n: '06', title: 'حافظ على خلوص الكهرباء', text: 'اعتبر كل سلك علوي مكهرباً حتى يؤكد المالك أو شركة الكهرباء غير ذلك ويُؤرّض بوضوح. حافظ على 10 أقدام (3.1 م) على الأقل من الخطوط حتى 50 كيلوفولت. فوق 50 كيلوفولت استخدم 10 أقدام إضافة إلى 0.4 بوصة لكل كيلوفولت زائد، أو ضعفي طول العازل، وبحد أدنى 10 أقدام. عيّن مراقباً عندما يصعب على المشغل تقدير الخلوص.', ref: '29 CFR 1926.600(a)(6)' },
      { n: '07', title: 'افصل الأشخاص عن الآلة', text: 'خطط مسارات باتجاه واحد وسرعات ومعابر وإضاءة ومناطق عزل. لا تقترب حتى يراك المشغل ويقر بوجودك وتتوقف المعدة وينخفض الملحق. لا تقف بين آلة وجسم ثابت أو تحت حمل مرفوع أو داخل نصف قطر الدوران. استخدم حواجز وموجهاً عند ضعف الرؤية. الملابس العاكسة لا تستبدل الفصل المادي.', ref: '29 CFR 1926.200; 1926.201; 1926.600; 1926.602' },
      { n: '08', title: 'أوقف العمل عند العيب أو فقد التواصل أو تغير الظروف', text: 'يوقف المشغل المعدة عند دخول شخص للمنطقة أو تعطل الإنذار أو الفرامل أو التوجيه أو عدم استقرار الأرض أو الحمل الزائد أو التسرب أو ضعف الرؤية أو فقد الإشارة. لا يجوز الضغط عليه للاستمرار. أعد الفحص بعد الإصلاح أو تغيير الملحق أو الصدمة أو النقل. تذكر: افحص، اعزل، تواصل، شغّل، ثم أوقف وثبّت.', ref: '29 CFR 1926.20(b); 1926.600; 1926.602' },
    ],
    quiz: [
      { q: 'متى ترجع معدة رؤيتها الخلفية محجوبة؟', a: ['بعد تشغيل البوق فقط', 'مع إنذار رجوع عامل أو عامل يوجّه بأمان', 'عند غياب المشرف', 'ببطء دون إنذار'], correct: 1 },
      { q: 'ماذا يلزم عند الوقوف على منحدر؟', a: ['فرامل الوقوف وموانع العجلات', 'رفع الجرافة', 'ترك ناقل الحركة للأمام', 'ترك المحرك يعمل'], correct: 0 },
      { q: 'ما الخلوص المعتاد من خط حتى 50 كيلوفولت؟', a: ['3 أقدام', '6 أقدام', '8 أقدام', '10 أقدام'], correct: 3 },
      { q: 'من يركب الشاحنة الصناعية؟', a: ['أي عامل بخوذة', 'شخص مصرح له وله مكان ركوب آمن', 'من يمسك الإطار', 'الموجّه على الشوك'], correct: 1 },
      { q: 'ما الذي يسند الجرافة المرفوعة للصيانة؟', a: ['الضغط الهيدروليكي', 'زميل عند التحكم', 'تدعيم أو حشو قوي', 'فرامل الوقوف فقط'], correct: 2 },
    ],
  },
  ur: {
    slides: [
      { n: '01', title: 'صرف تربیت یافتہ مجاز operator چلائے', text: 'آجر operator کی equipment اور workplace کے مطابق training اور evaluation یقینی بنائے۔ شفٹ سے پہلے brakes، steering، horn، reverse alarm، lights، tires/tracks، guards، seat belt، ROPS، mirrors، leaks اور attachments چیک کریں۔ rated capacity اور manufacturer instructions دیکھیں۔ safety defect والی مشین tag out کریں۔', ref: '29 CFR 1926.20(b)(4); 1926.602(a), (d); 1910.178(l)' },
      { n: '02', title: 'seat belt پہنیں اور protective zone میں رہیں', text: 'ROPS یا مناسب canopy والی متعلقہ earthmoving equipment میں seat belt استعمال کریں۔ چلتی یا الٹتی مشین سے نہ کودیں؛ بیٹھے رہیں اور belt باندھے رکھیں۔ powered industrial truck پر unauthorized rider منع ہے؛ authorized rider کے لیے محفوظ جگہ ضروری ہے۔ bucket، forks یا step پر کسی کو نہ لے جائیں۔', ref: '29 CFR 1926.602(a)(2), (b)(1), (c)(1)(vii)' },
      { n: '03', title: 'reverse صرف alarm یا signaler کے ساتھ', text: 'bidirectional machine میں site noise سے نمایاں horn ضروری ہے۔ rear view obstructed ہو تو earthmoving/compacting equipment صرف واضح reverse alarm چلنے یا employee کے safe signal پر reverse ہو۔ signaler سے visual contact ختم ہو تو فوراً رکیں۔ pedestrian-free zone بنائیں؛ camera blind spots ختم نہیں کرتا۔', ref: '29 CFR 1926.602(a)(9)' },
      { n: '04', title: 'park کرتے وقت lower، neutral، brake، chock', text: 'parking brake لگائیں؛ slope پر wheels chock بھی کریں۔ blade، bucket اور dump body نیچے کریں یا secure block کریں۔ raised part کے نیچے کام سے پہلے substantial blocking/cribbing کریں، controls neutral، motor بند اور brakes set ہوں جب تک کام کے لیے دوسری حالت ضروری نہ ہو۔ hydraulic pressure support نہیں۔', ref: '29 CFR 1926.600(a)(3)' },
      { n: '05', title: 'capacity، grade اور edge stability کا احترام', text: 'صرف equipment کے لیے بنے اور maintained road/grade استعمال کریں۔ emergency ramp/berm runaway vehicle روکے اور brakes fully loaded machine کو روک کر hold کریں۔ lift truck کی capacity واضح ہو اور exceed نہ ہو؛ capacity بدلنے والی modification کے لیے manufacturer کی written approval اور نئی plate چاہیے۔ excavation اور soft shoulder سے competent-person assessment کے مطابق دور رہیں۔', ref: '29 CFR 1926.602(a)(3)–(4), (c)(1)(i)–(iii)' },
      { n: '06', title: 'بجلی سے clearance رکھیں', text: 'ہر overhead wire energized سمجھیں جب تک utility اسے deenergized اور visibly grounded نہ بتائے۔ 50 kV یا کم line سے کم از کم 10 ft (3.1 m) دور رہیں۔ 50 kV سے اوپر 10 ft کے علاوہ ہر اضافی kV پر 0.4 in، یا insulator length کا دو گنا، مگر کبھی 10 ft سے کم نہیں۔ operator clearance نہ دیکھ سکے تو designated observer رکھیں۔', ref: '29 CFR 1926.600(a)(6)' },
      { n: '07', title: 'لوگوں اور مشین میں separation رکھیں', text: 'one-way routes، speed، crossings، lighting اور exclusion zones بنائیں۔ eye contact، operator acknowledgement، machine stop اور attachment ground ہونے کے بعد ہی قریب جائیں۔ moving machine اور fixed object کے درمیان، raised load کے نیچے یا swing radius میں نہ کھڑے ہوں۔ restricted visibility میں barrier اور spotter استعمال کریں۔ hi-vis separation کا بدل نہیں۔', ref: '29 CFR 1926.200; 1926.201; 1926.600; 1926.602' },
      { n: '08', title: 'defect، lost communication یا changed condition پر رکیں', text: 'لوگ zone میں ہوں، alarm، brake یا steering fail ہو، ground unstable، overload، leak، poor visibility یا signal contact lost ہو تو operator مشین روکے۔ supervisor جاری رکھنے کا دباؤ نہ دے۔ repair، attachment change، impact یا relocation کے بعد دوبارہ inspect کریں۔ یاد رکھیں: inspect، isolate، communicate، operate، پھر park and secure۔', ref: '29 CFR 1926.20(b); 1926.600; 1926.602' },
    ],
    quiz: [
      { q: 'rear view obstructed earthmover کب reverse ہو؟', a: ['صرف horn پر', 'واضح reverse alarm یا safe signal دینے والے employee کے ساتھ', 'supervisor نہ ہو', 'بغیر alarm آہستہ'], correct: 1 },
      { q: 'slope پر parking کی شرط؟', a: ['parking brake اور wheel chocks', 'bucket اوپر', 'forward gear', 'engine چلتا رہے'], correct: 0 },
      { q: '50 kV یا کم line سے عام minimum clearance؟', a: ['3 ft', '6 ft', '8 ft', '10 ft'], correct: 3 },
      { q: 'powered industrial truck پر کون ride کرے؟', a: ['helmet والا ہر شخص', 'authorized شخص جس کے لیے safe place ہو', 'frame پکڑنے والا', 'forks پر signaler'], correct: 1 },
      { q: 'maintenance میں raised bucket کو کیا support کرے؟', a: ['hydraulic pressure', 'controls پر coworker', 'substantial blocking/cribbing', 'صرف parking brake'], correct: 2 },
    ],
  },
  hi: {
    slides: [
      { n: '01', title: 'केवल प्रशिक्षित अधिकृत ऑपरेटर चलाए', text: 'नियोक्ता उपकरण और स्थल के अनुसार ऑपरेटर प्रशिक्षण और मूल्यांकन सुनिश्चित करे। शिफ्ट से पहले ब्रेक, स्टीयरिंग, हॉर्न, रिवर्स अलार्म, लाइट, टायर/ट्रैक, गार्ड, सीट बेल्ट, ROPS, दर्पण, रिसाव और अटैचमेंट जाँचें। रेटेड क्षमता और निर्माता निर्देश देखें। सुरक्षा दोष वाली मशीन टैग आउट करें।', ref: '29 CFR 1926.20(b)(4); 1926.602(a), (d); 1910.178(l)' },
      { n: '02', title: 'सीट बेल्ट पहनें और सुरक्षा क्षेत्र में रहें', text: 'ROPS या उचित कैनोपी वाली संबंधित अर्थमूविंग मशीन में सीट बेल्ट उपयोग करें। चलती या पलटती मशीन से न कूदें; बैठे रहें और बेल्ट बाँधे रखें। औद्योगिक ट्रक पर अनधिकृत सवारी निषिद्ध है; अधिकृत सवार के लिए सुरक्षित स्थान चाहिए। बकेट, फोर्क या स्टेप पर व्यक्ति न ले जाएँ।', ref: '29 CFR 1926.602(a)(2), (b)(1), (c)(1)(vii)' },
      { n: '03', title: 'रिवर्स केवल अलार्म या सिग्नलर के साथ', text: 'दो-दिशा मशीन में स्थल शोर से अलग सुनाई देने वाला हॉर्न हो। पीछे दृश्य बाधित हो तो मशीन केवल चालू स्पष्ट रिवर्स अलार्म या सुरक्षित संकेत देने वाले कर्मचारी के साथ रिवर्स हो। सिग्नलर से दृश्य संपर्क टूटे तो तुरंत रुकें। पैदल-मुक्त क्षेत्र बनाएँ; कैमरा ब्लाइंड स्पॉट समाप्त नहीं करता।', ref: '29 CFR 1926.602(a)(9)' },
      { n: '04', title: 'पार्क करें: नीचे, न्यूट्रल, ब्रेक और चॉक', text: 'पार्किंग ब्रेक लगाएँ; ढलान पर पहियों को चॉक भी करें। ब्लेड, बकेट और डम्प बॉडी नीचे करें या सुरक्षित ब्लॉक करें। उठे भाग के नीचे काम से पहले मजबूत ब्लॉकिंग/क्रिबिंग दें, नियंत्रण न्यूट्रल, मोटर बंद और ब्रेक लगे हों जब तक कार्य अन्यथा न माँगे। हाइड्रोलिक दबाव सहारा नहीं है।', ref: '29 CFR 1926.600(a)(3)' },
      { n: '05', title: 'क्षमता, ढलान और किनारे की स्थिरता मानें', text: 'उपकरण के लिए बने और रखरखाव किए मार्ग/ढलान उपयोग करें। आपात रैम्प/बर्म भागती गाड़ी रोके और ब्रेक पूर्ण भार वाली मशीन रोककर थामें। लिफ्ट ट्रक क्षमता साफ दिखाई दे और न लाँघें; क्षमता बदलने वाले संशोधन हेतु निर्माता की लिखित स्वीकृति और बदली प्लेट चाहिए। खुदाई और कमजोर किनारे से सक्षम-व्यक्ति आकलन अनुसार दूर रहें।', ref: '29 CFR 1926.602(a)(3)–(4), (c)(1)(i)–(iii)' },
      { n: '06', title: 'विद्युत दूरी बनाए रखें', text: 'हर ऊपर तार को जीवित मानें जब तक उपयोगिता उसे बंद और स्पष्ट ग्राउंड न करे। 50 kV या कम लाइन से कम-से-कम 10 ft (3.1 m) रहें। 50 kV से ऊपर 10 ft plus प्रत्येक अतिरिक्त kV पर 0.4 in, या इंसुलेटर लंबाई का दो गुना—कभी 10 ft से कम नहीं। ऑपरेटर दूरी न आँक सके तो नियुक्त पर्यवेक्षक रखें।', ref: '29 CFR 1926.600(a)(6)' },
      { n: '07', title: 'लोगों और मशीन को अलग रखें', text: 'एक-दिशा मार्ग, गति, क्रॉसिंग, प्रकाश और बहिष्करण क्षेत्र बनाएँ। आँख संपर्क, ऑपरेटर स्वीकृति, मशीन रुकने और अटैचमेंट जमीन पर होने के बाद ही पास जाएँ। चलती मशीन और स्थिर वस्तु के बीच, उठे भार के नीचे या स्विंग क्षेत्र में न खड़े हों। सीमित दृश्य में अवरोध और स्पॉटर लगाएँ। हाई-विज कपड़ा अलगाव का विकल्प नहीं।', ref: '29 CFR 1926.200; 1926.201; 1926.600; 1926.602' },
      { n: '08', title: 'दोष, संपर्क टूटने या दशा बदलने पर रोकें', text: 'लोग क्षेत्र में हों, अलार्म/ब्रेक/स्टीयरिंग खराब, भूमि अस्थिर, अधिक भार, रिसाव, कमजोर दृश्य या संकेत संपर्क खो जाए तो ऑपरेटर मशीन रोके। पर्यवेक्षक जारी रखने का दबाव न दे। मरम्मत, अटैचमेंट बदलाव, टक्कर या स्थानांतरण बाद पुनः निरीक्षण करें। याद रखें: जाँच, अलगाव, संवाद, संचालन, फिर पार्क और सुरक्षित।', ref: '29 CFR 1926.20(b); 1926.600; 1926.602' },
    ],
    quiz: [
      { q: 'पीछे दृश्य बाधित अर्थमूवर कब रिवर्स हो?', a: ['केवल हॉर्न पर', 'स्पष्ट रिवर्स अलार्म या सुरक्षित संकेत देने वाले कर्मचारी के साथ', 'पर्यवेक्षक न हो', 'बिना अलार्म धीरे'], correct: 1 },
      { q: 'ढलान पर पार्किंग की आवश्यकता?', a: ['पार्किंग ब्रेक और व्हील चॉक', 'बकेट ऊपर', 'फॉरवर्ड गियर', 'इंजन चलता रहे'], correct: 0 },
      { q: '50 kV या कम लाइन से सामान्य न्यूनतम दूरी?', a: ['3 ft', '6 ft', '8 ft', '10 ft'], correct: 3 },
      { q: 'औद्योगिक ट्रक पर कौन सवारी कर सकता है?', a: ['हेलमेट वाला कोई व्यक्ति', 'सुरक्षित स्थान वाला अधिकृत व्यक्ति', 'फ्रेम पकड़ने वाला', 'फोर्क पर सिग्नलर'], correct: 1 },
      { q: 'रखरखाव में उठे बकेट का सहारा क्या है?', a: ['हाइड्रोलिक दबाव', 'नियंत्रण पर सहकर्मी', 'मजबूत ब्लॉकिंग/क्रिबिंग', 'केवल पार्किंग ब्रेक'], correct: 2 },
    ],
  },
};

