import type { CourseLanguage, CourseLesson } from './course-catalog';

export const fallingObjectCourse: Record<CourseLanguage, CourseLesson> = {
  en: {
    slides: [
      { n: '01', title: 'Control the source, the path and the person below', text: 'A hard hat is the last line of defense—not permission to work below an uncontrolled drop hazard. First remove loose items, then secure tools and materials, install edge containment, and barricade the area where an object could land or bounce. Employees exposed to possible head injury from impact, falling or flying objects, or electrical shock and burns must wear compliant head protection. Stop work when people enter the exclusion zone or materials cannot be secured.', ref: '29 CFR 1926.100(a)–(b); 1926.501(c)' },
      { n: '02', title: 'Remember the toeboard numbers: 3½–¼–1–50', text: 'A toeboard used for falling-object protection must be at least 3½ in (9 cm) high, have no more than ¼ in (0.6 cm) clearance above the working surface, and be solid or have openings no larger than 1 in (2.5 cm). It must resist at least 50 lb (222 N) applied downward or outward. Install it along enough of the edge to protect everyone below. A loose, split, short or widely perforated board is not an acceptable toeboard.', ref: '29 CFR 1926.502(j)(1)–(3)' },
      { n: '03', title: 'Use screens when materials rise above the toeboard', text: 'If tools, equipment or materials are stacked higher than the toeboard, install paneling or screening from the platform or toeboard up to the guardrail toprail or midrail for enough distance to protect employees below. When guardrails provide falling-object protection, openings must be small enough to stop the actual objects present. Do not rely on mesh whose openings are larger than bolts, fittings or debris being handled.', ref: '29 CFR 1926.502(j)(4)–(5); 1926.451(h)(2)' },
      { n: '04', title: 'Barricade the drop zone or provide rated overhead protection', text: 'Below scaffolds, either barricade the complete area into which objects could fall and prohibit entry, or provide toeboards, small-opening guardrails, screens, debris nets, catch platforms or canopies strong enough for the expected impact. Canopies must be positioned between the hazard and workers and resist collapse and penetration. Oversized or heavy items that containment cannot stop must be moved away from the edge and secured. Never guess the drop zone—allow for deflection and bounce.', ref: '29 CFR 1926.451(h)(1)–(3); 1926.502(j)(8)' },
      { n: '05', title: 'Protect holes with secured, marked, twice-load covers', text: 'A floor or roof hole cover must be secured against displacement and color-coded or marked “HOLE” or “COVER.” In vehicle aisles it must support at least twice the maximum axle load of the largest vehicle expected. Elsewhere it must support at least twice the combined weight of employees, equipment and materials that may be on it at one time. Never shift, remove or partially uncover it without isolating the opening and providing the required fall and falling-object protection.', ref: '29 CFR 1926.502(i)(1)–(4)' },
      { n: '06', title: 'Keep materials back: roofing 6 feet, bricklaying 4 feet', text: 'During roofing, do not store materials or equipment within 6 ft (1.8 m) of a roof edge unless guardrails are installed at the edge; stacks near the edge must be stable and self-supporting. During overhand bricklaying, only masonry and mortar may be stored within 4 ft (1.2 m) of the working edge. Remove excess mortar, broken units and debris regularly. Wind, vibration and sloping surfaces can move a stable-looking stack—stop and restack it.', ref: '29 CFR 1926.502(j)(6)–(7)' },
      { n: '07', title: 'Never stand under a suspended load', text: 'Hoisting routes must minimize exposure. Only employees needed to receive a load may be in the fall zone while it is being landed, and they must not stand directly under it. Use qualified rigging, tag lines when appropriate, and controlled access; never use hands or feet to stop a swinging load. On scaffolds, control swinging loads that could strike the structure with tag lines or equivalent measures. Stop the lift for poor communication, uncontrolled swing, damaged rigging or an occupied fall zone.', ref: '29 CFR 1926.1425(a)–(c); 1926.451(f)(9)' },
      { n: '08', title: 'Inspect before the shift and whenever conditions change', text: 'The competent person checks edges, platforms, covers, toeboards, screens, nets, barricades, housekeeping and material stability before work and after wind, impact, lifting activity or layout changes. Workers secure small parts in closed containers and keep platforms free of accumulated debris. Protection must match the size, weight and path of the potential object. Memory rule: secure it, contain it, isolate below, then verify before work resumes.', ref: '29 CFR 1926.20(b); 1926.25; 1926.451(f)(3), (f)(13), (h)' },
    ],
    quiz: [
      { q: 'Which toeboard meets the minimum OSHA falling-object criteria?', a: ['3 in high with a ½-in bottom gap', '3½ in high, ¼-in maximum gap, 1-in maximum openings and 50-lb strength', '4 in high with unrestricted mesh openings', 'Any timber placed near the edge'], correct: 1 },
      { q: 'What must an ordinary hole cover support outside vehicle aisles?', a: ['At least twice the combined load that may be imposed at one time', 'Exactly one worker’s weight', 'The cover’s own weight only', 'A fixed 200 lb for every opening'], correct: 0 },
      { q: 'Materials are stacked above the toeboard. What is required?', a: ['Move workers closer so they can watch', 'A warning sign only', 'A second toeboard laid flat', 'Paneling or screening extending upward to the guardrail toprail or midrail'], correct: 3 },
      { q: 'Without edge guardrails, how close may roofing materials normally be stored to the roof edge?', a: ['2 ft', 'Not within 6 ft (1.8 m)', '4 ft', 'Any distance if tied with rope'], correct: 1 },
      { q: 'Who may be directly under a suspended load?', a: ['The signal person', 'Workers wearing hard hats', 'No employee', 'Only the rigger'], correct: 2 },
    ],
  },
  ar: {
    slides: [
      { n: '01', title: 'تحكم في المصدر والمسار ومن يوجد أسفل', text: 'الخوذة هي خط الدفاع الأخير وليست تصريحاً للعمل تحت خطر غير مسيطر عليه. أزل الأجسام السائبة، وثبّت الأدوات والمواد، وركّب حماية للحواف، واعزل المنطقة التي قد يسقط أو يرتد إليها الجسم. يجب ارتداء حماية رأس مطابقة عند التعرض للصدمات أو الأجسام الساقطة أو المتطايرة أو الصعق والحروق الكهربائية. أوقف العمل إذا دخل أحد منطقة العزل أو تعذر تثبيت المواد.', ref: '29 CFR 1926.100(a)–(b); 1926.501(c)' },
      { n: '02', title: 'تذكر أرقام حاجز القدم: 3½–¼–1–50', text: 'يكون ارتفاع حاجز القدم 3½ بوصة (9 سم) على الأقل، والخلوص أسفله لا يزيد على ¼ بوصة (0.6 سم)، ويكون مصمتاً أو فتحاته لا تتجاوز 1 بوصة (2.5 سم). يتحمل قوة 50 رطلاً (222 نيوتن) على الأقل إلى أسفل أو الخارج. ركّبه بطول كافٍ لحماية من هم أسفل. الحاجز القصير أو المتشقق أو غير المثبت غير مقبول.', ref: '29 CFR 1926.502(j)(1)–(3)' },
      { n: '03', title: 'استخدم الشِباك عندما تعلو المواد حاجز القدم', text: 'إذا ارتفعت الأدوات أو المواد فوق حاجز القدم، ركّب ألواحاً أو شِباكاً من المنصة أو الحاجز حتى الحاجز العلوي أو الأوسط ولمسافة تكفي لحماية العاملين أسفل. عندما يُستخدم نظام الحواجز لمنع سقوط الأجسام، يجب أن تكون فتحاته أصغر من الأجسام الفعلية الموجودة. لا تعتمد على شبكة تسمح بمرور المسامير أو الوصلات أو المخلفات.', ref: '29 CFR 1926.502(j)(4)–(5); 1926.451(h)(2)' },
      { n: '04', title: 'اعزل منطقة السقوط أو وفر حماية علوية مناسبة', text: 'أسفل السقالات، اعزل كامل المنطقة المحتمل وصول الأجسام إليها وامنع الدخول، أو استخدم حواجز قدم أو شِباك أو شبكات مخلفات أو منصات التقاط أو مظلات تتحمل الصدمة المتوقعة. توضع المظلة بين الخطر والعامل وتقاوم الانهيار والاختراق. تُبعد الأجسام الكبيرة أو الثقيلة عن الحافة وتُثبت. احسب الانحراف والارتداد ولا تكتفِ بالنقطة العمودية فقط.', ref: '29 CFR 1926.451(h)(1)–(3); 1926.502(j)(8)' },
      { n: '05', title: 'غطِّ الفتحات بغطاء مثبت ومعلّم يتحمل ضعفي الحمل', text: 'يُثبت غطاء فتحة الأرض أو السقف لمنع تحركه ويُلوّن أو يُكتب عليه “HOLE” أو “COVER”. في مسارات المركبات يتحمل ضعفي أكبر حمل محور متوقع. وفي الأماكن الأخرى يتحمل ضعفي مجموع وزن العمال والمعدات والمواد التي قد تكون عليه في وقت واحد. لا تحرك الغطاء دون عزل الفتحة وتوفير الحماية المطلوبة.', ref: '29 CFR 1926.502(i)(1)–(4)' },
      { n: '06', title: 'أبعد المواد: 6 أقدام للأسقف و4 أقدام للبناء', text: 'في أعمال الأسقف، لا تخزن مواد أو معدات ضمن 6 أقدام (1.8 م) من الحافة دون حواجز، وتكون الأكوام مستقرة وقائمة بذاتها. في البناء فوق اليد، لا يُخزن ضمن 4 أقدام (1.2 م) من الحافة إلا الطوب والمونة. أزل المونة الزائدة والوحدات المكسورة والمخلفات بانتظام. أوقف العمل وأعد الترصيص عند تأثير الرياح أو الاهتزاز أو الميل.', ref: '29 CFR 1926.502(j)(6)–(7)' },
      { n: '07', title: 'لا تقف أبداً تحت حمل معلّق', text: 'خطط مسار الرفع لتقليل التعرض. لا يدخل منطقة سقوط الحمل أثناء إنزاله إلا العاملون اللازمون لاستلامه، ولا يقف أحد تحته مباشرة. استخدم تجهيز رفع صحيحاً وحبال توجيه وعزلاً مناسباً، ولا توقف حملاً متأرجحاً باليد أو القدم. أوقف الرفع عند ضعف التواصل أو فقد التحكم أو تلف التجهيز أو دخول أحد منطقة الخطر.', ref: '29 CFR 1926.1425(a)–(c); 1926.451(f)(9)' },
      { n: '08', title: 'افحص قبل الوردية وعند تغير الظروف', text: 'يفحص الشخص المختص الحواف والمنصات والأغطية وحواجز القدم والشِباك ومناطق العزل والنظافة وثبات المواد قبل العمل وبعد الرياح أو الصدمات أو الرفع أو تغير الترتيب. احفظ القطع الصغيرة في حاويات مغلقة ولا تسمح بتراكم المخلفات. قاعدة التذكر: ثبّت الجسم، احتوه، اعزل من أسفل، ثم تحقق قبل استئناف العمل.', ref: '29 CFR 1926.20(b); 1926.25; 1926.451(f)(3), (f)(13), (h)' },
    ],
    quiz: [
      { q: 'أي حاجز قدم يحقق الحد الأدنى؟', a: ['3 بوصات وخلوص نصف بوصة', '3½ بوصة، خلوص ¼ بوصة، فتحات 1 بوصة، وقوة 50 رطلاً', '4 بوصات بأي فتحات', 'أي قطعة خشب قرب الحافة'], correct: 1 },
      { q: 'ما قدرة غطاء الفتحة خارج مسارات المركبات؟', a: ['ضعفا الحمل المجمع المتوقع في وقت واحد', 'وزن عامل واحد', 'وزنه الذاتي فقط', '200 رطل دائماً'], correct: 0 },
      { q: 'ماذا تفعل إذا علت المواد حاجز القدم؟', a: ['تقريب العمال للمراقبة', 'لافتة فقط', 'حاجز قدم ثانٍ مسطح', 'تركيب ألواح أو شِباك حتى الحاجز العلوي أو الأوسط'], correct: 3 },
      { q: 'دون حواجز، ما مسافة تخزين مواد الأسقف من الحافة؟', a: ['قدمين', 'لا تُخزن ضمن 6 أقدام', '4 أقدام', 'أي مسافة مع حبل'], correct: 1 },
      { q: 'من يجوز له الوقوف مباشرة تحت حمل معلّق؟', a: ['مسؤول الإشارة', 'من يرتدي خوذة', 'لا أحد', 'عامل التجهيز فقط'], correct: 2 },
    ],
  },
  ur: {
    slides: [
      { n: '01', title: 'ذریعہ، راستہ اور نیچے موجود شخص کو محفوظ کریں', text: 'ہیلمٹ آخری دفاع ہے، بے قابو خطرے کے نیچے کام کی اجازت نہیں۔ ڈھیلی چیزیں ہٹائیں، اوزار اور مواد محفوظ کریں، کنارے پر containment لگائیں اور ممکنہ گرنے یا اچھلنے کا علاقہ barricade کریں۔ impact، falling/flying objects یا برقی shock/burn کے خطرے میں منظور شدہ head protection پہنیں۔ کوئی exclusion zone میں آئے یا مواد محفوظ نہ ہو تو کام روکیں۔', ref: '29 CFR 1926.100(a)–(b); 1926.501(c)' },
      { n: '02', title: 'toeboard کے اعداد یاد رکھیں: 3½–¼–1–50', text: 'toeboard کم از کم 3½ انچ (9 سم) اونچا، سطح سے زیادہ سے زیادہ ¼ انچ (0.6 سم) gap، solid یا openings زیادہ سے زیادہ 1 انچ (2.5 سم) ہوں۔ وہ نیچے یا باہر لگنے والی کم از کم 50 lb (222 N) قوت برداشت کرے۔ نیچے موجود تمام افراد کے تحفظ کے لیے کافی لمبائی تک لگائیں۔ ڈھیلا، ٹوٹا یا چھوٹا board قابل قبول نہیں۔', ref: '29 CFR 1926.502(j)(1)–(3)' },
      { n: '03', title: 'مواد toeboard سے اونچا ہو تو screen لگائیں', text: 'اوزار یا مواد toeboard سے اونچا ہو تو platform یا toeboard سے guardrail کے toprail یا midrail تک paneling یا screening لگائیں۔ guardrail کو falling-object protection کے لیے استعمال کریں تو openings موجود چھوٹی اشیاء کو بھی روکیں۔ ایسی mesh پر بھروسا نہ کریں جس سے bolt، fitting یا debris گزر سکے۔', ref: '29 CFR 1926.502(j)(4)–(5); 1926.451(h)(2)' },
      { n: '04', title: 'drop zone بند کریں یا مضبوط overhead protection دیں', text: 'اسکیفولڈ کے نیچے مکمل ممکنہ drop/bounce area barricade کر کے داخلہ روکیں، یا toeboard، screen، debris net، catch platform یا expected impact برداشت کرنے والی canopy دیں۔ canopy خطرے اور کارکن کے درمیان ہو اور collapse یا penetration روکے۔ بہت بڑی یا بھاری اشیاء کنارے سے دور رکھ کر secure کریں۔ صرف سیدھا نیچے نہیں، deflection اور bounce بھی شمار کریں۔', ref: '29 CFR 1926.451(h)(1)–(3); 1926.502(j)(8)' },
      { n: '05', title: 'hole cover: secure، marked، اور دو گنا مضبوط', text: 'floor یا roof hole cover کو حرکت سے روکیں اور رنگ یا “HOLE/COVER” نشان لگائیں۔ vehicle aisle میں وہ سب سے بڑی متوقع گاڑی کے maximum axle load کا کم از کم دو گنا برداشت کرے۔ دوسری جگہ کارکنوں، سامان اور مواد کے ایک وقت کے combined load کا دو گنا برداشت کرے۔ opening isolate اور protection لگائے بغیر cover نہ ہٹائیں۔', ref: '29 CFR 1926.502(i)(1)–(4)' },
      { n: '06', title: 'مواد دور رکھیں: roofing 6 ft، bricklaying 4 ft', text: 'edge guardrail کے بغیر roofing material یا equipment roof edge کے 6 ft (1.8 m) اندر نہ رکھیں؛ stack stable اور self-supporting ہو۔ overhand bricklaying میں working edge کے 4 ft (1.2 m) اندر صرف masonry اور mortar ہو۔ اضافی mortar، ٹوٹی units اور debris باقاعدگی سے ہٹائیں۔ ہوا، vibration یا slope سے stack ہلے تو کام روک کر دوبارہ محفوظ کریں۔', ref: '29 CFR 1926.502(j)(6)–(7)' },
      { n: '07', title: 'suspended load کے نیچے کبھی نہ کھڑے ہوں', text: 'hoisting route exposure کم کرے۔ load land کرتے وقت صرف ضروری receiving کارکن fall zone میں ہوں اور کوئی براہِ راست نیچے نہ ہو۔ صحیح rigging، مناسب tag line اور controlled access استعمال کریں؛ ہاتھ یا پاؤں سے swinging load نہ روکیں۔ خراب communication، بے قابو swing، damaged rigging یا occupied fall zone پر lift روکیں۔', ref: '29 CFR 1926.1425(a)–(c); 1926.451(f)(9)' },
      { n: '08', title: 'شفٹ سے پہلے اور تبدیلی کے بعد معائنہ', text: 'competent person کام سے پہلے اور ہوا، impact، lifting یا layout change کے بعد edge، platform، cover، toeboard، screen، net، barricade، housekeeping اور stack stability چیک کرے۔ چھوٹے parts بند container میں رکھیں اور debris جمع نہ ہونے دیں۔ یاد رکھیں: secure، contain، نیچے isolate، پھر دوبارہ کام سے پہلے verify۔', ref: '29 CFR 1926.20(b); 1926.25; 1926.451(f)(3), (f)(13), (h)' },
    ],
    quiz: [
      { q: 'درست کم از کم toeboard کون سا ہے؟', a: ['3 in اونچا، ½ in gap', '3½ in اونچا، ¼ in gap، 1 in openings، 50 lb strength', '4 in اونچا، کوئی بھی mesh', 'کنارے پر کوئی لکڑی'], correct: 1 },
      { q: 'عام hole cover کتنی load capacity رکھے؟', a: ['ایک وقت کے combined load کا کم از کم دو گنا', 'ایک کارکن', 'صرف اپنا وزن', 'ہمیشہ 200 lb'], correct: 0 },
      { q: 'مواد toeboard سے اونچا ہو تو کیا کریں؟', a: ['کارکن قریب لائیں', 'صرف sign', 'دوسرا board flat رکھیں', 'toprail یا midrail تک panel/screen لگائیں'], correct: 3 },
      { q: 'guardrail نہ ہو تو roofing material edge سے کتنا دور؟', a: ['2 ft', 'کم از کم 6 ft باہر', '4 ft', 'rope ہو تو کہیں بھی'], correct: 1 },
      { q: 'suspended load کے بالکل نیچے کون ہو سکتا ہے؟', a: ['signal person', 'helmet والا کارکن', 'کوئی نہیں', 'صرف rigger'], correct: 2 },
    ],
  },
  hi: {
    slides: [
      { n: '01', title: 'स्रोत, रास्ता और नीचे के व्यक्ति को नियंत्रित करें', text: 'हेलमेट अंतिम सुरक्षा है, अनियंत्रित गिरावट के नीचे काम की अनुमति नहीं। ढीली वस्तुएँ हटाएँ, औजार और सामग्री सुरक्षित करें, किनारे पर रोक लगाएँ और संभावित गिरने/उछलने का क्षेत्र बैरिकेड करें। प्रभाव, गिरती/उड़ती वस्तु या विद्युत झटके/जलन के खतरे में अनुरूप सिर सुरक्षा पहनें। कोई बहिष्करण क्षेत्र में आए या सामग्री सुरक्षित न हो तो काम रोकें।', ref: '29 CFR 1926.100(a)–(b); 1926.501(c)' },
      { n: '02', title: 'टोबोर्ड संख्या याद रखें: 3½–¼–1–50', text: 'टोबोर्ड कम-से-कम 3½ in (9 cm) ऊँचा हो, सतह से खाली जगह अधिकतम ¼ in (0.6 cm), और ठोस या अधिकतम 1 in (2.5 cm) खुलाव वाला हो। वह नीचे या बाहर लगाई कम-से-कम 50 lb (222 N) शक्ति सहे। नीचे सभी लोगों की रक्षा हेतु पर्याप्त लंबाई में लगाएँ। ढीला, टूटा या छोटा बोर्ड स्वीकार्य नहीं।', ref: '29 CFR 1926.502(j)(1)–(3)' },
      { n: '03', title: 'सामग्री टोबोर्ड से ऊँची हो तो स्क्रीन लगाएँ', text: 'औजार या सामग्री टोबोर्ड से ऊपर हो तो प्लेटफॉर्म/टोबोर्ड से रेलिंग के टॉपरेल या मिडरेल तक पैनल या स्क्रीन लगाएँ। गिरती वस्तु रोकने वाली रेलिंग के खुलाव वास्तविक वस्तुओं को निकलने न दें। ऐसे जाल पर निर्भर न रहें जिससे बोल्ट, फिटिंग या मलबा गुजर सकता हो।', ref: '29 CFR 1926.502(j)(4)–(5); 1926.451(h)(2)' },
      { n: '04', title: 'ड्रॉप जोन रोकें या मजबूत ऊपरी सुरक्षा दें', text: 'मचान के नीचे पूरा संभावित गिरने और उछलने का क्षेत्र बैरिकेड कर प्रवेश रोकें, या टोबोर्ड, स्क्रीन, मलबा जाल, कैच प्लेटफॉर्म अथवा अपेक्षित प्रभाव सहने वाली कैनोपी दें। कैनोपी खतरे और कर्मचारी के बीच हो तथा ढहने और भेदन को रोके। बड़ी या भारी वस्तु किनारे से दूर सुरक्षित करें। केवल सीधी रेखा नहीं, उछाल भी गणना करें।', ref: '29 CFR 1926.451(h)(1)–(3); 1926.502(j)(8)' },
      { n: '05', title: 'छेद का कवर: सुरक्षित, चिह्नित और दो गुना मजबूत', text: 'फर्श या छत के कवर को खिसकने से रोकें और रंग या “HOLE/COVER” से चिह्नित करें। वाहन मार्ग में वह सबसे बड़े अपेक्षित वाहन के अधिकतम एक्सल भार का कम-से-कम दो गुना सहे। अन्य स्थान पर एक समय के कर्मचारी, उपकरण और सामग्री के संयुक्त भार का दो गुना सहे। छेद अलग और सुरक्षित किए बिना कवर न हटाएँ।', ref: '29 CFR 1926.502(i)(1)–(4)' },
      { n: '06', title: 'सामग्री दूर रखें: छत 6 फीट, ईंटकार्य 4 फीट', text: 'किनारे पर रेलिंग न हो तो छत सामग्री/उपकरण 6 ft (1.8 m) के भीतर न रखें; ढेर स्थिर और स्वयं टिकाऊ हो। ओवरहैंड ईंटकार्य में कार्य किनारे के 4 ft (1.2 m) भीतर केवल चिनाई और मसाला रखें। अतिरिक्त मसाला, टूटी इकाइयाँ और मलबा नियमित हटाएँ। हवा, कंपन या ढलान से ढेर हिले तो काम रोककर पुनः सुरक्षित करें।', ref: '29 CFR 1926.502(j)(6)–(7)' },
      { n: '07', title: 'निलंबित भार के नीचे कभी न खड़े हों', text: 'उठाने का मार्ग जोखिम कम करे। भार उतारते समय केवल आवश्यक प्राप्तकर्ता कर्मचारी फॉल जोन में हों और कोई सीधे नीचे न हो। सही रिगिंग, उपयुक्त टैग लाइन और नियंत्रित पहुँच उपयोग करें; हाथ-पैर से झूलता भार न रोकें। खराब संचार, अनियंत्रित झूलाव, क्षतिग्रस्त रिगिंग या भरे फॉल जोन पर लिफ्ट रोकें।', ref: '29 CFR 1926.1425(a)–(c); 1926.451(f)(9)' },
      { n: '08', title: 'शिफ्ट से पहले और बदलाव के बाद निरीक्षण करें', text: 'सक्षम व्यक्ति काम से पहले तथा हवा, प्रभाव, उठाने या लेआउट बदलाव के बाद किनारे, प्लेटफॉर्म, कवर, टोबोर्ड, स्क्रीन, जाल, बैरिकेड, सफाई और ढेर की स्थिरता जाँचे। छोटे भाग बंद डिब्बों में रखें और मलबा जमा न होने दें। याद रखें: सुरक्षित करें, रोकें, नीचे अलग करें, फिर काम शुरू करने से पहले सत्यापित करें।', ref: '29 CFR 1926.20(b); 1926.25; 1926.451(f)(3), (f)(13), (h)' },
    ],
    quiz: [
      { q: 'कौन-सा टोबोर्ड न्यूनतम मान पूरा करता है?', a: ['3 in ऊँचा, ½ in अंतर', '3½ in ऊँचा, ¼ in अंतर, 1 in खुलाव, 50 lb शक्ति', '4 in ऊँचा, कोई भी जाल', 'किनारे के पास कोई लकड़ी'], correct: 1 },
      { q: 'सामान्य छेद कवर क्या सह सके?', a: ['एक समय के संयुक्त भार का कम-से-कम दो गुना', 'एक कर्मचारी', 'केवल अपना वजन', 'हमेशा 200 lb'], correct: 0 },
      { q: 'सामग्री टोबोर्ड से ऊँची हो तो क्या करें?', a: ['कर्मचारी पास लाएँ', 'केवल संकेत', 'दूसरा बोर्ड समतल रखें', 'टॉपरेल या मिडरेल तक पैनल/स्क्रीन लगाएँ'], correct: 3 },
      { q: 'रेलिंग न हो तो छत सामग्री किनारे से कितनी दूर?', a: ['2 ft', 'कम-से-कम 6 ft बाहर', '4 ft', 'रस्सी हो तो कहीं भी'], correct: 1 },
      { q: 'निलंबित भार के सीधे नीचे कौन हो सकता है?', a: ['सिग्नल व्यक्ति', 'हेलमेट वाला कर्मचारी', 'कोई कर्मचारी नहीं', 'केवल रिगर'], correct: 2 },
    ],
  },
};
