import type { CourseLanguage,CourseLesson } from './course-catalog';
import { topicQuizzes } from './topic-quizzes';
type L={t:string;x:string;ref:string}; type P={s:L[];q:{q:string;a:string[];correct:number}[]};
const localize=(en:P,labels:Record<Exclude<CourseLanguage,'en'>,{t:string[];x:string[];q:string[];a:string[][]}>):Record<CourseLanguage,CourseLesson>=>{
 const out:any={en:{slides:en.s.map((z,i)=>({n:String(i+1).padStart(2,'0'),title:z.t,text:z.x,ref:z.ref})),quiz:en.q}};
 for(const lang of ['ar','ur','hi'] as const){const p=labels[lang];out[lang]={slides:p.t.map((t,i)=>({n:String(i+1).padStart(2,'0'),title:t,text:p.x[i],ref:en.s[i].ref})),quiz:p.q.map((q,i)=>({q,a:p.a[i],correct:en.q[i].correct}))};} return out;
};
const mk=(s:L[],q:P['q'],ar:any,ur:any,hi:any)=>localize({s,q},{ar,ur,hi});

export const fireCourse=mk([
{t:'Remove or shield fire hazards',x:'Move hot work to a designated safe place when practical. Otherwise remove movable combustibles and positively confine sparks, heat and slag with suitable screens or blankets. Do not weld, cut or heat where flammable coatings, compounds or heavy dust create a hazard.',ref:'1926.352(a)–(c)'},
{t:'Keep extinguishing equipment ready',x:'Suitable extinguishing equipment must be immediately available and ready for instant use. For general construction, provide at least one 2A extinguisher per 3,000 ft² of protected building area with no more than 100 ft travel; provide a 10B extinguisher within 50 ft where more than 5 gal flammable liquid or 5 lb flammable gas is used.',ref:'1926.150(c)(1); 1926.150(c)(1)(vi)'},
{t:'Assign and train the fire watch',x:'Maintain the fire watch during hot work and for at least 30 minutes after welding or cutting ends to detect and extinguish possible smoldering fires. Continue longer whenever hazards or the hot-work permit require it, and until no possibility of fire remains. The watch knows the specific hazards, alarm method, escape route and extinguisher use.',ref:'1910.252(a)(2)(iii)(B); 1926.352(e)'},
{t:'Check the opposite side',x:'Heat and sparks can penetrate or conduct through walls, floors and ceilings. Apply the same controls on the opposite side and check hidden voids, penetrations, ducts and lower levels. Stop if the fire watch cannot observe every exposed area.',ref:'1926.352(f)'},
{t:'Control cylinders and hoses',x:'Keep cylinders secured upright, caps on when not connected, and oxygen separated from fuel gas by 20 ft or a noncombustible barrier at least 5 ft high with a 30-minute fire-resistance rating. Inspect hoses and fittings; keep oil and grease away from oxygen equipment.',ref:'1926.350(a),(j)'},
{t:'Shut gas off outside enclosed spaces',x:'When a torch is unused or left unattended for a substantial time, positively close its gas supply outside the enclosed space. At shift change and overnight remove torch and hose; immediately remove disconnected open-ended fuel-gas and oxygen hoses.',ref:'1926.352(g)'},
{t:'Make containers safe before heating',x:'Keep flammable-liquid containers closed except during transfer. Before hot work on a drum or hollow structure that held toxic or flammable material, fill with water or thoroughly clean, ventilate and test it. Provide a vent before heating so pressure cannot build.',ref:'1926.352(h)–(j)'},
{t:'Stop and raise the alarm',x:'Stop for combustible dust, gas odor, leaking hose, missing extinguisher, uncontrolled sparks, damaged screens, unsafe opposite side or changing conditions. A fire watch raises the alarm and uses an extinguisher only while escape remains safe; emergency response is not a reason to become trapped.',ref:'1926.150; 1926.352'}
],[
{q:'What is the minimum fire-watch period after welding or cutting ends?',a:['30 minutes','60 minutes','90 minutes','No post-work watch is required'],correct:0},
{q:'Maximum travel distance to a general 2A extinguisher is:',a:['25 ft','50 ft','100 ft','150 ft'],correct:2},
{q:'Standard oxygen/fuel-gas cylinder separation is:',a:['20 ft or the specified 5-ft rated barrier','5 ft only','10 ft or plywood','No separation if capped'],correct:0},
{q:'Hot work on a drum that held flammable material may start after:',a:['Opening the lid','Thorough cleaning/ventilation/testing or filling with water, plus pressure venting','A smell test','Painting the drum'],correct:1},
{q:'Sparks can penetrate a wall. What is required?',a:['Watch only the welding side','Wet the electrode','Apply equivalent precautions on the opposite side','Close the room'],correct:2}
],
{t:['أزل أو احمِ مخاطر الحريق','جهز معدات الإطفاء','عيّن ودرّب مراقب الحريق','افحص الجانب الآخر','سيطر على الأسطوانات والخراطيم','أغلق الغاز خارج المكان','أمّن الأوعية قبل التسخين','توقف وأطلق الإنذار'],x:['انقل العمل الساخن لمكان آمن أو أزل المواد القابلة للاشتعال واعزل الشرر والحرارة والخبث. لا تعمل مع طلاء قابل للاشتعال أو غبار كثيف.','وفر مطفأة مناسبة جاهزة: 2A لكل 3000 قدم² وبمسافة سير أقصاها 100 قدم؛ و10B خلال 50 قدماً عند أكثر من 5 جالونات سائل أو 5 أرطال غاز قابل للاشتعال.','أبقِ مراقب الحريق أثناء العمل الساخن ولمدة لا تقل عن 30 دقيقة بعد انتهاء اللحام أو القطع لاكتشاف وإطفاء الحرائق الكامنة. استمر مدة أطول إذا تطلبت المخاطر أو تصريح العمل الساخن ذلك، وحتى التأكد من عدم بقاء احتمال للحريق. يجب أن يعرف المراقب المخاطر وطريقة الإنذار ومسار الهروب واستخدام المطفأة.','طبّق الضوابط نفسها على الجهة الأخرى للجدار/الأرضية/السقف وافحص الفراغات والفتحات والمستويات الأدنى.','ثبّت الأسطوانات وافصل الأكسجين عن الوقود 20 قدماً أو بحاجز غير قابل للاحتراق ارتفاعه 5 أقدام ومقاوم 30 دقيقة. أبعد الزيت عن الأكسجين.','عند ترك الشعلة أغلق الغاز من خارج المكان. عند نهاية الوردية أو الليل أخرج الشعلة والخرطوم، وأخرج الخراطيم المفتوحة المفصولة فوراً.','أبق الأوعية مغلقة. قبل تسخين وعاء سابق لمادة خطرة املأه ماء أو نظفه وهوّه واختبره، وافتح منفذاً للضغط.','توقف عند الغبار أو رائحة الغاز أو التسرب أو غياب المطفأة أو شرر غير محكوم. أطلق الإنذار ولا تكافح إلا مع بقاء الهروب آمناً.'],q:['ما الحد الأدنى لمدة استمرار مراقب الحريق بعد انتهاء اللحام أو القطع؟','أقصى مسافة إلى 2A؟','فصل أسطوانات الأكسجين والوقود؟','متى يسخن وعاء سابق لمادة قابلة للاشتعال؟','الشرر يخترق الجدار؛ ماذا تفعل؟'],a:[['30 دقيقة','60 دقيقة','90 دقيقة','لا تلزم مراقبة بعد العمل'],['25','50','100','150'],['20 قدماً أو حاجز 5 أقدام محدد','5 فقط','10 وخشب','لا فصل'],['فتح الغطاء','تنظيف/تهوية/اختبار أو ماء مع منفذ ضغط','الشم','الدهان'],['راقب جهة واحدة','بلل القطب','احتياطات مماثلة بالجهة الأخرى','أغلق الغرفة']]},
{t:['آگ کے خطرے ہٹائیں','extinguisher تیار','fire watch مقرر','دوسری طرف چیک','cylinders/hoses قابو','gas باہر بند','container محفوظ','رکیں اور alarm'],x:['hot work محفوظ مقام لے جائیں یا combustibles ہٹا کر sparks/heat/slag روکیں۔ flammable coating یا heavy dust میں کام نہیں۔','2A فی 3000 ft² اور زیادہ سے زیادہ 100 ft travel؛ 5 gal liquid یا 5 lb gas سے زیادہ پر 10B 50 ft کے اندر تیار ہو۔','fire watch کو hot work کے دوران اور welding یا cutting ختم ہونے کے بعد کم از کم 30 منٹ تک برقرار رکھیں تاکہ سلگتی آگ کا پتہ لگا کر اسے بجھایا جا سکے۔ خطرات یا hot-work permit کے تقاضے کے مطابق، اور آگ کا امکان ختم ہونے تک، زیادہ دیر جاری رکھیں۔ watch کو hazards، alarm، escape route اور extinguisher کا استعمال معلوم ہو۔','walls/floor/ceiling کی دوسری جانب بھی وہی controls؛ voids، openings، lower levels چیک کریں۔','cylinders upright secure؛ oxygen/fuel 20 ft یا 5-ft noncombustible 30-min barrier۔ oxygen سے oil/grease دور۔','torch unattended ہو تو gas enclosed space کے باہر بند؛ shift/night پر torch/hose باہر؛ disconnected open hoses فوراً باہر۔','flammable container بند۔ سابق toxic/flammable drum کو water fill یا clean/ventilate/test اور heating سے پہلے pressure vent دیں۔','dust، gas smell، leak، missing extinguisher، uncontrolled sparks یا unsafe opposite side پر رکیں۔ alarm دیں؛ escape safe ہو تو ہی extinguisher۔'],q:['welding یا cutting ختم ہونے کے بعد fire watch کی کم از کم مدت کیا ہے؟','2A تک max travel؟','oxygen/fuel separation؟','flammable drum پر hot work کب؟','spark wall پار کرے؟'],a:[['30 منٹ','60 منٹ','90 منٹ','کام کے بعد watch ضروری نہیں'],['25','50','100','150'],['20 ft یا specified 5-ft barrier','5 only','10/wood','none'],['lid open','clean/vent/test یا water plus vent','smell','paint'],['ایک side','electrode wet','دوسری طرف برابر controls','room close']]},
{t:['आग खतरे हटाएँ','extinguisher तैयार','fire watch नियुक्त','दूसरी तरफ जाँच','cylinder/hose नियंत्रण','gas बाहर बंद','container सुरक्षित','रोकें और alarm'],x:['hot work सुरक्षित जगह ले जाएँ या combustibles हटाकर sparks/heat/slag रोकें। flammable coating या heavy dust में काम नहीं।','2A प्रति 3000 ft² और अधिकतम 100 ft travel; 5 gal liquid या 5 lb gas से अधिक पर 10B 50 ft में तैयार।','hot work के दौरान और welding या cutting समाप्त होने के बाद कम-से-कम 30 मिनट तक fire watch बनाए रखें ताकि सुलगती आग का पता लगाकर उसे बुझाया जा सके। खतरे या hot-work permit की आवश्यकता के अनुसार, और आग की कोई संभावना न रहने तक, इसे अधिक समय जारी रखें। watch को hazards, alarm, escape route और extinguisher का उपयोग पता हो।','wall/floor/ceiling के दूसरी ओर भी समान नियंत्रण; void, opening और नीचे स्तर जाँचें।','cylinder upright secure; oxygen/fuel 20 ft या 5-ft noncombustible 30-min barrier। oxygen से oil/grease दूर।','torch unattended हो तो gas enclosed space के बाहर बंद; shift/night पर torch/hose बाहर; खुले disconnected hose तुरंत बाहर।','flammable container बंद। पुराने toxic/flammable drum को water fill या clean/ventilate/test करें और heating से पहले pressure vent दें।','dust, gas smell, leak, missing extinguisher, uncontrolled sparks या unsafe opposite side पर रोकें। alarm दें; escape सुरक्षित हो तभी extinguisher।'],q:['welding या cutting समाप्त होने के बाद fire watch की न्यूनतम अवधि क्या है?','2A तक max travel?','oxygen/fuel separation?','flammable drum पर hot work कब?','spark wall पार करे?'],a:[['30 मिनट','60 मिनट','90 मिनट','काम के बाद watch आवश्यक नहीं'],['25','50','100','150'],['20 ft या specified 5-ft barrier','5 only','10/wood','none'],['lid open','clean/vent/test या water plus vent','smell','paint'],['एक side','electrode wet','दूसरी तरफ समान controls','room बंद']]});

const compact=(title:string,refs:string[],facts:string[],correct=[1,2,0,3,1],localized?:Partial<Record<CourseLanguage,string[]>>):Record<CourseLanguage,CourseLesson>=>{
 const labels={ar:['القاعدة','القياس','الشخص المسؤول','طريقة العمل','الفحص','منطقة الخطر','الإيقاف','تذكر'],ur:['اصول','پیمائش','ذمہ دار شخص','محفوظ طریقہ','معائنہ','خطرہ زون','کام روکیں','یاد رکھیں'],hi:['नियम','माप','जिम्मेदार व्यक्ति','सुरक्षित विधि','निरीक्षण','खतरा क्षेत्र','काम रोकें','याद रखें']};
 const prefix={ar:'تدريب عملي: ',ur:'عملی تربیت: ',hi:'व्यावहारिक प्रशिक्षण: '};
 const qs:any={
  en:[['What must control the work?',['Guesswork','The cited OSHA rule and site hazard assessment','PPE alone','Production target']],['Who verifies changing conditions?',['Visitor','Any passer-by','The designated competent/authorized person for the task','Driver']],['When must work stop?',['When a required control fails','Only after injury','At lunch only','When the job is nearly done']],['May a site rule be more protective than OSHA minimum?',['Never','Only verbally','Only at night','Yes']],['What should a worker do before starting?',['Begin and ask later','Understand the hazards, controls and stop-work triggers','Rely on memory only','Remove warnings']]],
  ar:[['ما الذي يحكم العمل؟',['التخمين','نص OSHA وتقييم مخاطر الموقع','PPE وحده','هدف الإنتاج']],['من يتحقق من تغير الظروف؟',['زائر','أي عابر','الشخص المختص/المصرح للمهمة','السائق']],['متى يتوقف العمل؟',['عند فشل ضابط مطلوب','بعد إصابة فقط','وقت الغداء','قرب النهاية']],['هل يمكن لقاعدة الموقع أن تكون أشد حماية؟',['أبداً','شفهياً فقط','ليلاً فقط','نعم']],['ماذا يفعل العامل قبل البدء؟',['يبدأ ثم يسأل','يفهم الأخطار والضوابط وأسباب الإيقاف','يعتمد الذاكرة','يزيل التحذير']]],
  ur:[['کام کس کے مطابق؟',['اندازہ','OSHA rule اور site hazard assessment','صرف PPE','production target']],['بدلتے حالات کون verify کرے؟',['visitor','کوئی بھی','task کا competent/authorized person','driver']],['کام کب رکے؟',['required control fail پر','صرف injury بعد','lunch پر','اختتام قریب']],['site rule OSHA minimum سے زیادہ protective ہو سکتا؟',['نہیں','صرف زبانی','صرف رات','ہاں']],['شروع سے پہلے worker؟',['شروع پھر پوچھے','hazards, controls, stop triggers سمجھے','صرف memory','warning ہٹائے']]],
  hi:[['काम किसके अनुसार?',['अनुमान','OSHA rule और site hazard assessment','केवल PPE','production target']],['बदलती दशा कौन सत्यापित करे?',['visitor','कोई भी','task का competent/authorized person','driver']],['काम कब रोके?',['required control fail पर','केवल injury बाद','lunch पर','अंत निकट']],['site rule OSHA minimum से अधिक protective हो सकता?',['नहीं','केवल मौखिक','केवल रात','हाँ']],['शुरू से पहले worker?',['शुरू फिर पूछे','hazards, controls, stop triggers समझे','केवल memory','warning हटाए']]]};
 const quizSet=title.startsWith('Housekeeping')?topicQuizzes.housekeeping:title.startsWith('Excavation')?topicQuizzes.excavation:title.startsWith('Electrical')?topicQuizzes.electrical:topicQuizzes.loto;
 const base:any={}; for(const lang of ['en','ar','ur','hi'] as CourseLanguage[]){const body=localized?.[lang]||facts;base[lang]={slides:body.map((x,i)=>({n:String(i+1).padStart(2,'0'),title:lang==='en'?`${title}: ${['rule','measure','responsibility','safe method','inspection','danger zone','stop work','memory check'][i]}`:labels[lang as 'ar'][i],text:lang==='en'?x:prefix[lang as 'ar']+x,ref:refs[i]})),quiz:quizSet.text[lang].map((z,i)=>({q:z.q,a:z.a,correct:quizSet.correct[i]}))};} return base;
};

export const housekeepingCourse=compact('Housekeeping & Foreign Object Debris (FOD)',Array(8).fill('29 CFR 1926.25; 1926.252'),[
'Keep work areas, passageways and stairs clear of scrap, protruding nails, loose materials, cords and spills. Remove combustible scrap and debris at regular intervals; do not wait for shift end when accumulation creates a hazard.',
'Use covered containers for oily or hazardous waste. When dropping material more than 20 ft outside a building, use an enclosed chute. Guard a floor/opening used for disposal with a barricade at least 42 in high and post warning signs.',
'Assign ownership by zone and shift. Supervisors inspect; every worker controls tools, fasteners, packaging and personal items. FOD is an industry control concept: OSHA does not prescribe one universal FOD count or zone size.',
'Inventory small items before and after work, cap open pipes, cover intakes, tether tools where falling-object assessment requires, segregate waste and use magnets/screens/vacuums suited to the material. Never use compressed air in a way that spreads contamination or exposes workers.',
'Inspect access routes continuously and after deliveries, weather and work changes. Record missing tools or parts and search before energizing, closing equipment, concrete placement or turnover. A clean-looking area can still contain hidden FOD.',
'Establish red zones below overhead work and around sensitive equipment. Secure materials against wind and vibration. Do not throw material freely; use chutes, hoists or controlled lowering and protect workers below.',
'Stop for blocked exit, unstable stack, sharp scrap, spill, missing tool, open component, uncontrolled waste drop or combustible accumulation. Isolate the area, correct the cause and report any item that may have entered equipment.',
'Memory rule: clean as you go, count what enters, count what leaves, protect openings, and verify before close-up. Housekeeping prevents slips, fire, struck-by events and equipment damage; it is a production control, not decoration.'
],[1,2,0,3,1],{
ar:['حافظ على مناطق العمل والممرات والسلالم خالية من الخردة والمسامير البارزة والمواد والأسلاك والانسكابات. أزل النفايات القابلة للاشتعال دورياً ولا تنتظر نهاية الوردية إذا أصبح التراكم خطراً.','استخدم أوعية مغطاة للنفايات الزيتية أو الخطرة. عند إسقاط مواد من أكثر من 20 قدماً خارج المبنى استخدم مزلقاً مغلقاً. احط فتحة التخلص بحاجز ارتفاعه 42 بوصة على الأقل مع تحذير.','حدد مسؤولية كل منطقة ووردية. يفحص المشرف ويتحكم كل عامل في أدواته ومثبتاته وعبواته. FOD مفهوم صناعي؛ لا تحدد OSHA عدداً عاماً أو مساحة ثابتة لمنطقته.','عدّ القطع الصغيرة قبل العمل وبعده، وأغلق الأنابيب وغط المداخل واربط الأدوات عند لزوم تقييم الأجسام الساقطة. افصل النفايات ولا تستخدم الهواء المضغوط لنشر التلوث أو تعريض العمال.','افحص طرق الوصول باستمرار وبعد التوريد والطقس وتغير العمل. سجل الأداة أو القطعة المفقودة وابحث عنها قبل التشغيل أو إغلاق المعدة أو صب الخرسانة أو التسليم.','أنشئ منطقة حمراء أسفل العمل العلوي وحول المعدات الحساسة وثبت المواد ضد الرياح والاهتزاز. لا ترم المواد؛ استخدم مزلقاً أو رافعة أو إنزالاً محكوماً واحم من في الأسفل.','توقف عند مخرج مسدود أو رصة غير ثابتة أو خردة حادة أو انسكاب أو أداة مفقودة أو إسقاط نفايات غير محكوم أو تراكم قابل للاشتعال. اعزل وصحح وأبلغ.','تذكر: نظف أثناء العمل، وعد ما يدخل وما يخرج، واحم الفتحات وتحقق قبل الإغلاق. النظافة تمنع الانزلاق والحريق والاصطدام وتلف المعدات.'],
ur:['work areas، راستے اور سیڑھیاں scrap، نکلے nails، loose material، cords اور spills سے صاف رکھیں۔ combustible waste باقاعدہ ہٹائیں؛ hazard بنے تو shift end تک انتظار نہیں۔','oily/hazardous waste covered containers میں۔ building سے باہر 20 ft سے زیادہ drop پر enclosed chute۔ disposal opening پر کم از کم 42-in barricade اور warning۔','ہر zone/shift کا owner مقرر۔ supervisor inspect اور ہر worker tools، fasteners، packaging/personal items قابو کرے۔ FOD industry concept ہے؛ OSHA universal count یا zone size نہیں دیتا۔','کام سے پہلے/بعد small items count، pipes cap، intakes cover، assessment پر tools tether، waste segregate۔ compressed air سے contamination نہ پھیلائیں یا workers expose نہ ہوں۔','routes مسلسل اور delivery، weather، change بعد inspect۔ missing tool/part record اور energize، close-up، concrete یا handover سے پہلے تلاش۔ صاف نظر آنے میں hidden FOD ہو سکتا۔','overhead work کے نیچے اور sensitive equipment گرد red zone۔ wind/vibration کے خلاف material secure۔ آزاد پھینکنا نہیں؛ chute/hoist/controlled lowering اور نیچے protection۔','blocked exit، unstable stack، sharp scrap، spill، missing tool، open component، uncontrolled drop یا combustible build-up پر stop، isolate، correct، report۔','یاد: ساتھ ساتھ صاف، داخل/خارج چیز count، openings protect، close-up سے پہلے verify۔ housekeeping slip، fire، struck-by اور damage روکتی ہے۔'],
hi:['कार्य क्षेत्र, रास्ते और सीढ़ियाँ scrap, निकले nails, loose material, cords और spills से साफ रखें। combustible waste नियमित हटाएँ; hazard बने तो shift end तक न प्रतीक्षा करें।','oily/hazardous waste covered containers में रखें। building से बाहर 20 ft से अधिक drop पर enclosed chute। disposal opening पर कम-से-कम 42-in barricade और warning।','हर zone/shift का owner तय करें। supervisor inspect करे और हर worker tools, fasteners, packaging/personal items नियंत्रित करे। FOD industry concept है; OSHA universal count या zone size नहीं देता।','काम से पहले/बाद small items गिनें, pipes cap, intakes cover, assessment पर tools tether, waste अलग। compressed air से contamination न फैलाएँ या workers expose न हों।','routes लगातार और delivery, weather, change बाद inspect करें। missing tool/part दर्ज कर energize, close-up, concrete या handover से पहले खोजें। साफ दिखने में hidden FOD हो सकता है।','overhead work के नीचे और sensitive equipment आसपास red zone। wind/vibration के विरुद्ध material secure। स्वतंत्र न फेंकें; chute/hoist/controlled lowering और नीचे protection।','blocked exit, unstable stack, sharp scrap, spill, missing tool, open component, uncontrolled drop या combustible build-up पर stop, isolate, correct, report।','याद रखें: साथ-साथ साफ करें, अंदर/बाहर वस्तु गिनें, openings बचाएँ, close-up से पहले verify। housekeeping slip, fire, struck-by और damage रोकती है।']
});

export const excavationCourse=compact('Excavation & Trenching',Array(8).fill('29 CFR 1926.650–1926.652; Subpart P Apps A–F'),[
'A competent person who can identify hazards and promptly correct them classifies soil and selects/monitors controls. A trench is a narrow excavation no wider than 15 ft at its bottom. Locate underground utilities before digging and protect them while exposed.',
'Protect workers from cave-in at 5 ft (1.52 m) or deeper unless entirely stable rock; below 5 ft a competent person may determine no cave-in hazard exists. Excavations deeper than 20 ft require a protective system designed or approved by a registered professional engineer.',
'Use sloping, benching, shoring or shielding selected from the standard, tabulated data or engineered design. Maximum simple slopes are Type A 3/4H:1V, Type B 1H:1V and Type C 1.5H:1V; layered, fissured or previously disturbed soil may force a weaker classification.',
'For trenches 4 ft (1.22 m) or deeper, provide ladder, stair, ramp or other safe egress so no worker travels more than 25 ft (7.62 m) laterally. Ladders must be secured and extend as required for safe access; never climb shoring or a trench box.',
'Keep spoil, equipment and materials at least 2 ft (0.61 m) from the edge or use retaining devices. Protect workers from traffic with high-visibility garments and controls; keep them out from under loads handled by lifting/digging equipment.',
'Test atmospheres in excavations over 4 ft deep where oxygen deficiency or hazardous atmosphere could reasonably exist. Provide ventilation or respiratory protection as required, rescue equipment, and do not allow water accumulation without competent-person-controlled precautions.',
'The competent person inspects daily before work, as needed during the shift, and after rainstorms or other hazard-increasing events. Workers leave immediately for cracks, sloughing, bulging/heaving bottom, water, protective-system movement, vibration damage or atmospheric alarm.',
'A trench box protects only workers inside its protected area; never remain inside while it is installed, removed or moved vertically. Excavation may extend up to 2 ft below a shield only when designed for full depth and soil loss is not indicated.'
],[1,2,0,3,1],{
ar:['يصنف شخص مختص التربة ويختار ويراقب الحماية. الخندق حفر ضيق لا يزيد عرضه السفلي عن 15 قدماً. حدد المرافق تحت الأرض قبل الحفر واحمها عند كشفها.','احم العمال من الانهيار عند عمق 5 أقدام (1.52م) فأكثر إلا في الصخر المستقر؛ تحت 5 أقدام يقرر المختص عدم وجود الخطر. أعمق من 20 قدماً يتطلب نظاماً يصممه أو يعتمده مهندس مهني مسجل.','استخدم الميل أو المصاطب أو التدعيم أو الدرع وفق المعيار والبيانات أو التصميم. أقصى ميل بسيط: A ‏0.75H:1V، B ‏1H:1V، C ‏1.5H:1V؛ التربة المتشققة أو المضطربة قد تصنف أضعف.','في خندق عمقه 4 أقدام (1.22م) فأكثر وفر سلماً أو درجاً أو منحدراً بحيث لا يتجاوز الانتقال الجانبي 25 قدماً (7.62م). ثبت السلم ولا تتسلق التدعيم أو الصندوق.','أبعد ناتج الحفر والمعدات والمواد 2 قدم (0.61م) على الأقل عن الحافة أو استخدم حواجز. احم من المرور وأبعد العمال عن الأحمال المرفوعة.','اختبر الجو في حفر أعمق من 4 أقدام إذا أمكن نقص الأكسجين أو وجود جو خطير. وفر التهوية/التنفس والإنقاذ ولا تسمح بتراكم الماء دون احتياطات يضبطها المختص.','يفحص المختص يومياً قبل العمل وأثناءه حسب الحاجة وبعد المطر أو أي زيادة للخطر. اخرج فوراً عند الشقوق أو تساقط التربة أو انتفاخ القاع أو الماء أو حركة النظام أو إنذار الجو.','يحمي صندوق الخندق من بداخله فقط؛ لا تبق داخله عند تركيبه أو نزعه أو تحريكه رأسياً. يسمح بالحفر حتى قدمين أسفله فقط إذا صمم للعمق الكامل ولا تظهر خسارة تربة.'],
ur:['competent person soil classify اور controls select/monitor کرے۔ trench bottom پر 15 ft سے زیادہ چوڑی نہیں۔ digging سے پہلے underground utilities locate اور exposed حالت میں protect۔','5 ft (1.52m) یا گہری excavation میں cave-in protection، سوائے مکمل stable rock؛ 5 ft سے کم پر competent person no hazard طے کرے۔ 20 ft سے زیادہ system registered professional engineer design/approve۔','standard/data/design کے مطابق slope، bench، shore یا shield۔ max simple slopes: Type A 0.75H:1V، B 1H:1V، C 1.5H:1V؛ fissured/disturbed soil weaker ہو سکتی۔','4 ft (1.22m) یا گہری trench میں ladder/stair/ramp، lateral travel زیادہ سے زیادہ 25 ft (7.62m)۔ ladder secure؛ shoring یا trench box پر نہ چڑھیں۔','spoil، equipment/material edge سے کم از کم 2 ft (0.61m) یا retaining device۔ traffic controls/hi-vis اور lifting/digging loads کے نیچے workers نہیں۔','4 ft سے زیادہ میں atmosphere test جہاں oxygen deficiency/hazard ممکن۔ ventilation/respiratory/rescue دیں؛ competent-person precautions کے بغیر water accumulation نہیں۔','competent person روز work سے پہلے، shift میں ضرورت پر، rain یا hazard event بعد inspect۔ cracks، slough، heave، water، system movement، vibration damage یا alarm پر فوراً باہر۔','trench box صرف اندر protected area۔ install/remove/vertical move میں اندر نہیں۔ shield bottom سے 2 ft نیچے صرف full-depth design اور soil loss کی علامت نہ ہو۔'],
hi:['competent person soil classify और controls select/monitor करे। trench नीचे 15 ft से अधिक चौड़ी नहीं। digging से पहले underground utilities locate और exposed अवस्था में protect करें।','5 ft (1.52m) या गहरी excavation में cave-in protection, पूर्ण stable rock को छोड़कर; 5 ft से कम पर competent person no hazard तय करे। 20 ft से अधिक system registered professional engineer design/approve करे।','standard/data/design अनुसार slope, bench, shore या shield। max simple slopes: Type A 0.75H:1V, B 1H:1V, C 1.5H:1V; fissured/disturbed soil weaker हो सकती है।','4 ft (1.22m) या गहरी trench में ladder/stair/ramp, lateral travel अधिकतम 25 ft (7.62m)। ladder secure; shoring या trench box पर न चढ़ें।','spoil, equipment/material edge से कम-से-कम 2 ft (0.61m) या retaining device। traffic controls/hi-vis और lifting/digging loads के नीचे workers नहीं।','4 ft से अधिक में atmosphere test जहाँ oxygen deficiency/hazard संभव। ventilation/respiratory/rescue दें; competent-person precautions बिना water accumulation नहीं।','competent person रोज work से पहले, shift में जरूरत पर, rain या hazard event बाद inspect करे। cracks, slough, heave, water, system movement, vibration damage या alarm पर तुरंत बाहर।','trench box केवल protected area के अंदर बचाता है। install/remove/vertical move में अंदर न रहें। shield से 2 ft नीचे तभी जब full-depth design हो और soil loss संकेत न हो।']
});

export const electricalCourse=compact('Electrical Safety',Array(8).fill('29 CFR 1926 Subpart K; 1926.403–1926.417'),[
'Only qualified persons work on energized parts. Deenergize, lock/tag and verify whenever feasible. Guard live parts operating at 50 volts or more against accidental contact by enclosure, location, partition or elevation; treat damaged insulation as energized exposure.',
'On construction sites protect 120-V, single-phase, 15- and 20-amp receptacles not part of permanent wiring with GFCIs or a written assured equipment grounding conductor program. The program is not a casual substitute: it requires a designated person, inspections, tests and records.',
'Under an assured grounding program, visually inspect cord sets and plug-connected equipment before each day’s use. Test grounding continuity and correct terminal connection before first use, after repair, after suspected damage, and at intervals not over 3 months (6 months for fixed, nonexposed cords).',
'Use flexible cords only for permitted temporary purposes. Protect from sharp edges and damage; do not run through holes, doors, windows or attach to building surfaces in prohibited ways. Never lift equipment by its cord or remove the grounding pin.',
'Temporary lights need guards where bulbs may be struck; metal-shell lampholders must be grounded. Keep wet-location equipment approved for the location, hands dry, and connections elevated/protected. A GFCI reduces shock risk but does not make unsafe work acceptable.',
'Maintain required approach distance from overhead lines and have the utility deenergize/ground or use specified guarding. For cranes, covered equipment normally stays at least 10 ft from lines up to 50 kV; use the applicable larger distance at higher voltage.',
'Inspect panels, cords, tools and GFCIs before use. Close unused openings, label circuits, maintain working clearance and use rated covers. Stop for missing ground, exposed conductor, heat, odor, arcing, tripping GFCI, water entry or an unidentified supply.',
'In an electrical contact, do not touch the person or equipment until energy is isolated. Call emergency help, use trained rescue/CPR response and suitable nonconductive methods only within training. Report and quarantine involved equipment before reuse.'
],[1,2,0,3,1],{
ar:['يعمل على الأجزاء المكهربة أشخاص مؤهلون فقط. افصل الطاقة واقفل/علّم وتحقق متى أمكن. احجب الأجزاء الحية عند 50 فولت فأكثر؛ اعتبر العزل التالف تعرضاً مكهرباً.','احم مقابس 120V أحادية الطور 15/20A غير الدائمة بـGFCI أو برنامج مكتوب مضمون لموصل التأريض. يلزم شخص معين وفحوص واختبارات وسجلات.','في برنامج التأريض افحص الأسلاك والمعدات قبل الاستخدام اليومي. اختبر الاستمرارية والتوصيل قبل أول استخدام وبعد الإصلاح/الضرر وبفاصل لا يتجاوز 3 أشهر، أو 6 أشهر للسلك الثابت غير المعرض.','استخدم الأسلاك المرنة فقط مؤقتاً حيث يسمح. احمها من الحواف ولا تمررها بفتحات أو أبواب بطرق محظورة. لا ترفع الأداة بسلكها ولا تنزع سن التأريض.','احم المصابيح المؤقتة المعرضة للصدم وأرض حامل المعدن. استخدم معدات معتمدة للمكان الرطب وارفع الوصلات. GFCI يقلل الخطر ولا يبرر عملاً غير آمن.','حافظ على مسافة خطوط الكهرباء واجعل المرفق يفصل ويؤرض أو استخدم الحماية المحددة. للمعدات المغطاة قرب خطوط حتى 50kV تكون المسافة المعتادة 10 أقدام على الأقل، وتزداد مع الجهد.','افحص اللوحات والأسلاك والأدوات وGFCI. أغلق الفتحات وعرّف الدوائر وحافظ على الخلوص. توقف عند فقد التأريض أو موصل مكشوف أو حرارة أو قوس أو ماء أو مصدر مجهول.','عند التماس لا تلمس الشخص أو المعدة حتى عزل الطاقة. اتصل بالطوارئ واستخدم إنقاذاً وCPR مدرباً ووسيلة غير موصلة ضمن التدريب. اعزل المعدات قبل إعادة الاستخدام.'],
ur:['energized parts پر صرف qualified persons۔ feasible ہو تو deenergize، lock/tag، verify۔ 50V یا زیادہ live parts guard؛ damaged insulation کو energized exposure سمجھیں۔','construction کے nonpermanent 120V single-phase 15/20A receptacles کو GFCI یا written assured grounding program۔ program میں designated person، inspections، tests، records لازم۔','assured program میں cords/equipment روز استعمال سے پہلے visual check۔ continuity/terminal test first use، repair، suspected damage اور زیادہ سے زیادہ 3 ماہ؛ fixed unexposed cords 6 ماہ۔','flexible cords صرف allowed temporary use۔ sharp edges/damage سے بچائیں؛ prohibited holes/doors/windows نہیں۔ cord سے tool نہ اٹھائیں اور ground pin نہ نکالیں۔','temporary bulbs جہاں strike ہو guard، metal lampholder ground۔ wet-location approved equipment، dry hands، protected connections۔ GFCI unsafe work کو safe نہیں بناتا۔','overhead line distance رکھیں؛ utility deenergize/ground یا specified guard۔ covered equipment عام طور پر 50kV تک کم از کم 10 ft؛ higher voltage پر larger distance۔','panels، cords، tools، GFCIs pre-use inspect۔ openings close، circuits label، clearance/covers۔ missing ground، exposed wire، heat، smell، arc، trip، water یا unknown supply پر stop۔','contact میں energy isolate تک person/equipment نہ چھوئیں۔ emergency call، trained rescue/CPR اور nonconductive method صرف training کے اندر۔ equipment quarantine۔'],
hi:['energized parts पर केवल qualified persons। feasible हो तो deenergize, lock/tag, verify। 50V या अधिक live parts guard; damaged insulation को energized exposure मानें।','construction के nonpermanent 120V single-phase 15/20A receptacles को GFCI या written assured grounding program। program में designated person, inspections, tests, records जरूरी।','assured program में cords/equipment रोज उपयोग से पहले visual check। continuity/terminal test first use, repair, suspected damage और अधिकतम 3 माह; fixed unexposed cords 6 माह।','flexible cords केवल allowed temporary use। sharp edges/damage से बचाएँ; prohibited holes/doors/windows नहीं। cord से tool न उठाएँ और ground pin न निकालें।','temporary bulbs जहाँ strike हो guard, metal lampholder ground। wet-location approved equipment, dry hands, protected connections। GFCI unsafe work को safe नहीं बनाता।','overhead line distance रखें; utility deenergize/ground या specified guard। covered equipment सामान्यतः 50kV तक कम-से-कम 10 ft; higher voltage पर larger distance।','panels, cords, tools, GFCIs pre-use inspect। openings close, circuits label, clearance/covers। missing ground, exposed wire, heat, smell, arc, trip, water या unknown supply पर stop।','contact में energy isolate तक person/equipment न छुएँ। emergency call, trained rescue/CPR और nonconductive method केवल training में। equipment quarantine करें।']
});

export const lotoCourse=compact('Lockout/Tagout',Array(8).fill('29 CFR 1926.417; 29 CFR 1910.147 where applicable'),[
'Before work on circuits or equipment, identify every electrical, mechanical, hydraulic, pneumatic, chemical, thermal, gravity and stored-energy source. Notify affected employees and use the energy-control procedure applicable to the equipment—not just the stop button.',
'Controls of deenergized electrical equipment must be tagged, and circuits must be rendered inoperative. Tags identify the equipment/circuit and warn against operation. Where a lock can be applied under the applicable energy-control rule, use each authorized employee’s personal lock.',
'Authorized employees apply lockout and perform servicing; affected employees operate/use the machine or work nearby; other employees must not restart or tamper. Affected and other employees receive role-appropriate instruction; only authorized employees execute energy isolation.',
'Shut down normally, isolate every source, apply locks/tags, release or restrain stored energy, and verify isolation. Block raised parts, discharge capacitors, bleed pressure, restrain springs and address reaccumulation. Pressing start is only one part of verification.',
'Before work, an authorized employee verifies zero-energy condition with properly rated/tested instruments and attempts normal controls safely. For electrical testing, test the meter on a known source before and after (live-dead-live) under the employer’s safe-work procedure.',
'For group lockout, each authorized worker applies a personal lock or equivalent control to the group device and remains protected during shift changes. The primary authorized employee coordinates scope, status and handover; never share one anonymous lock.',
'Normally only the employee who applied a lock removes it. An employer exception requires a specific documented procedure, verification the employee is absent, reasonable contact efforts, and informing that employee before resuming work. Never cut a lock for convenience.',
'Before reenergizing, inspect the area, remove tools, replace guards, confirm people are clear, remove devices by authorized procedure and notify affected employees. Stop for unidentified energy, missing isolation point, failed test, changed scope or a person whose protection is uncertain.'
],[1,2,0,3,1],{
ar:['قبل العمل حدد كل مصادر الطاقة الكهربائية والميكانيكية والهيدروليكية والهوائية والكيميائية والحرارية والجاذبية والمخزنة. أخطر المتأثرين واتبع إجراء المعدة؛ زر الإيقاف لا يكفي.','تُعلّم مفاتيح المعدات الكهربائية المفصولة وتصبح الدائرة غير قابلة للتشغيل. تحدد البطاقة المعدة وتحذر. حيث ينطبق القفل يستخدم كل عامل مصرح قفله الشخصي.','العامل المصرح يعزل ويخدم؛ العامل المتأثر يشغل المعدة أو يعمل قربها؛ لا يعيد الآخرون التشغيل أو يعبثون. التدريب حسب الدور والعزل للمصرح فقط.','أوقف طبيعياً واعزل كل مصدر وضع القفل/البطاقة وفرغ أو قيّد الطاقة المخزنة ثم تحقق. ادعم الأجزاء المرفوعة وفرغ المكثف والضغط وثبت النوابض.','يتحقق عامل مصرح من انعدام الطاقة بأداة مصنفة ومختبرة ويجرب التحكم بأمان. في الكهرباء اختبر المقياس على مصدر معروف قبل الاختبار وبعده: حي-ميت-حي.','في القفل الجماعي يضع كل مصرح قفله الشخصي أو حماية مكافئة على جهاز المجموعة وتستمر الحماية بين الورديات. ينسق المسؤول النطاق والحالة والتسليم؛ لا تشارك قفلاً مجهولاً.','عادة يزيل القفل من وضعه فقط. الاستثناء يتطلب إجراء موثقاً والتحقق من غياب العامل ومحاولة الاتصال وإبلاغه قبل عودته. لا تقطع القفل للراحة.','قبل إعادة الطاقة افحص وأزل الأدوات وأعد الحواجز وتأكد من خلو الناس وأزل الأجهزة بالإجراء وأخطر المتأثرين. توقف عند طاقة مجهولة أو نقطة عزل مفقودة أو اختبار فاشل أو تغير النطاق.'],
ur:['work سے پہلے ہر electrical، mechanical، hydraulic، pneumatic، chemical، thermal، gravity اور stored energy source identify۔ affected employees notify اور equipment procedure؛ stop button کافی نہیں۔','deenergized electrical controls tag اور circuit inoperative۔ tag equipment/circuit اور warning بتائے۔ جہاں lock applicable ہر authorized employee اپنا personal lock۔','authorized employee isolation/service؛ affected machine use یا near؛ others restart/tamper نہیں۔ role training؛ energy isolation صرف authorized۔','normal shutdown، ہر source isolate، locks/tags، stored energy release/restrain، verify۔ raised parts block، capacitors discharge، pressure bleed، springs restrain، reaccumulation control۔','authorized employee rated/tested instrument اور safe control attempt سے zero energy verify۔ electrical meter known live source پر before/after: live-dead-live۔','group lockout میں ہر authorized worker personal lock/equivalent group device پر؛ shift change میں protection۔ primary authorized scope/status/handover coordinate؛ anonymous lock share نہیں۔','عام طور پر lock لگانے والا ہی remove۔ exception میں documented procedure، employee absent verification، contact کوشش، اور return سے پہلے اطلاع۔ convenience کے لیے lock cut نہیں۔','reenergize سے پہلے area inspect، tools remove، guards replace، people clear، authorized removal اور affected notify۔ unknown energy، missing point، failed test، changed scope یا uncertain protection پر stop۔'],
hi:['work से पहले हर electrical, mechanical, hydraulic, pneumatic, chemical, thermal, gravity और stored energy source पहचानें। affected employees notify और equipment procedure; stop button पर्याप्त नहीं।','deenergized electrical controls tag और circuit inoperative। tag equipment/circuit और warning बताए। जहाँ lock applicable, हर authorized employee अपना personal lock लगाए।','authorized employee isolation/service; affected machine use या पास काम; others restart/tamper नहीं। role training; energy isolation केवल authorized।','normal shutdown, हर source isolate, locks/tags, stored energy release/restrain, verify। raised parts block, capacitors discharge, pressure bleed, springs restrain, reaccumulation control।','authorized employee rated/tested instrument और safe control attempt से zero energy verify करे। electrical meter known live source पर before/after: live-dead-live।','group lockout में हर authorized worker personal lock/equivalent group device पर लगाए; shift change में protection। primary authorized scope/status/handover coordinate; anonymous lock share नहीं।','सामान्यतः lock लगाने वाला ही हटाए। exception में documented procedure, employee absence verification, contact प्रयास और return से पहले सूचना। सुविधा हेतु lock न काटें।','reenergize से पहले area inspect, tools remove, guards replace, people clear, authorized removal और affected notify। unknown energy, missing point, failed test, changed scope या uncertain protection पर stop।']
});

