import type { CourseLanguage,CourseLesson } from './course-catalog';
type L={t:string;x:string;ref:string}; type P={s:L[];q:{q:string;a:string[];correct:number}[]};
const localize=(en:P,labels:Record<Exclude<CourseLanguage,'en'>,{t:string[];x:string[];q:string[];a:string[][]}>):Record<CourseLanguage,CourseLesson>=>{
 const out:any={en:{slides:en.s.map((z,i)=>({n:String(i+1).padStart(2,'0'),title:z.t,text:z.x,ref:z.ref})),quiz:en.q}};
 for(const lang of ['ar','ur','hi'] as const){const p=labels[lang];out[lang]={slides:p.t.map((t,i)=>({n:String(i+1).padStart(2,'0'),title:t,text:p.x[i],ref:en.s[i].ref})),quiz:p.q.map((q,i)=>({q,a:p.a[i],correct:en.q[i].correct}))};} return out;
};
const mk=(s:L[],q:P['q'],ar:any,ur:any,hi:any)=>localize({s,q},{ar,ur,hi});

export const fireCourse=mk([
{t:'Remove or shield fire hazards',x:'Move hot work to a designated safe place when practical. Otherwise remove movable combustibles and positively confine sparks, heat and slag with suitable screens or blankets. Do not weld, cut or heat where flammable coatings, compounds or heavy dust create a hazard.',ref:'1926.352(a)–(c)'},
{t:'Keep extinguishing equipment ready',x:'Suitable extinguishing equipment must be immediately available and ready for instant use. For general construction, provide at least one 2A extinguisher per 3,000 ft² of protected building area with no more than 100 ft travel; provide a 10B extinguisher within 50 ft where more than 5 gal flammable liquid or 5 lb flammable gas is used.',ref:'1926.150(c)(1); 1926.150(c)(1)(vi)'},
{t:'Assign and train the fire watch',x:'When normal precautions are insufficient, assign additional personnel during hot work and for enough time afterward to ensure no possibility of fire remains. OSHA construction does not prescribe one universal 30- or 60-minute watch. The watch knows the specific hazards, alarm method, escape route and extinguisher use.',ref:'1926.352(e)'},
{t:'Check the opposite side',x:'Heat and sparks can penetrate or conduct through walls, floors and ceilings. Apply the same controls on the opposite side and check hidden voids, penetrations, ducts and lower levels. Stop if the fire watch cannot observe every exposed area.',ref:'1926.352(f)'},
{t:'Control cylinders and hoses',x:'Keep cylinders secured upright, caps on when not connected, and oxygen separated from fuel gas by 20 ft or a noncombustible barrier at least 5 ft high with a 30-minute fire-resistance rating. Inspect hoses and fittings; keep oil and grease away from oxygen equipment.',ref:'1926.350(a),(j)'},
{t:'Shut gas off outside enclosed spaces',x:'When a torch is unused or left unattended for a substantial time, positively close its gas supply outside the enclosed space. At shift change and overnight remove torch and hose; immediately remove disconnected open-ended fuel-gas and oxygen hoses.',ref:'1926.352(g)'},
{t:'Make containers safe before heating',x:'Keep flammable-liquid containers closed except during transfer. Before hot work on a drum or hollow structure that held toxic or flammable material, fill with water or thoroughly clean, ventilate and test it. Provide a vent before heating so pressure cannot build.',ref:'1926.352(h)–(j)'},
{t:'Stop and raise the alarm',x:'Stop for combustible dust, gas odor, leaking hose, missing extinguisher, uncontrolled sparks, damaged screens, unsafe opposite side or changing conditions. A fire watch raises the alarm and uses an extinguisher only while escape remains safe; emergency response is not a reason to become trapped.',ref:'1926.150; 1926.352'}
],[
{q:'OSHA construction requires a universal fire-watch period of:',a:['30 minutes','60 minutes','90 minutes','No fixed period; long enough to ensure no possibility of fire remains'],correct:3},
{q:'Maximum travel distance to a general 2A extinguisher is:',a:['25 ft','50 ft','100 ft','150 ft'],correct:2},
{q:'Standard oxygen/fuel-gas cylinder separation is:',a:['20 ft or the specified 5-ft rated barrier','5 ft only','10 ft or plywood','No separation if capped'],correct:0},
{q:'Hot work on a drum that held flammable material may start after:',a:['Opening the lid','Thorough cleaning/ventilation/testing or filling with water, plus pressure venting','A smell test','Painting the drum'],correct:1},
{q:'Sparks can penetrate a wall. What is required?',a:['Watch only the welding side','Wet the electrode','Apply equivalent precautions on the opposite side','Close the room'],correct:2}
],
{t:['أزل أو احمِ مخاطر الحريق','جهز معدات الإطفاء','عيّن ودرّب مراقب الحريق','افحص الجانب الآخر','سيطر على الأسطوانات والخراطيم','أغلق الغاز خارج المكان','أمّن الأوعية قبل التسخين','توقف وأطلق الإنذار'],x:['انقل العمل الساخن لمكان آمن أو أزل المواد القابلة للاشتعال واعزل الشرر والحرارة والخبث. لا تعمل مع طلاء قابل للاشتعال أو غبار كثيف.','وفر مطفأة مناسبة جاهزة: 2A لكل 3000 قدم² وبمسافة سير أقصاها 100 قدم؛ و10B خلال 50 قدماً عند أكثر من 5 جالونات سائل أو 5 أرطال غاز قابل للاشتعال.','عند عدم كفاية الاحتياطات عيّن مراقباً أثناء العمل وبعده مدة تكفي لانعدام احتمال الحريق. لا تحدد OSHA مدة عامة 30/60 دقيقة. يعرف الخطر والإنذار والهروب والمطفأة.','طبّق الضوابط نفسها على الجهة الأخرى للجدار/الأرضية/السقف وافحص الفراغات والفتحات والمستويات الأدنى.','ثبّت الأسطوانات وافصل الأكسجين عن الوقود 20 قدماً أو بحاجز غير قابل للاحتراق ارتفاعه 5 أقدام ومقاوم 30 دقيقة. أبعد الزيت عن الأكسجين.','عند ترك الشعلة أغلق الغاز من خارج المكان. عند نهاية الوردية أو الليل أخرج الشعلة والخرطوم، وأخرج الخراطيم المفتوحة المفصولة فوراً.','أبق الأوعية مغلقة. قبل تسخين وعاء سابق لمادة خطرة املأه ماء أو نظفه وهوّه واختبره، وافتح منفذاً للضغط.','توقف عند الغبار أو رائحة الغاز أو التسرب أو غياب المطفأة أو شرر غير محكوم. أطلق الإنذار ولا تكافح إلا مع بقاء الهروب آمناً.'],q:['مدة مراقبة الحريق العامة؟','أقصى مسافة إلى 2A؟','فصل أسطوانات الأكسجين والوقود؟','متى يسخن وعاء سابق لمادة قابلة للاشتعال؟','الشرر يخترق الجدار؛ ماذا تفعل؟'],a:[['30 دقيقة','60','90','لا مدة ثابتة؛ حتى زوال الاحتمال'],['25','50','100','150'],['20 قدماً أو حاجز 5 أقدام محدد','5 فقط','10 وخشب','لا فصل'],['فتح الغطاء','تنظيف/تهوية/اختبار أو ماء مع منفذ ضغط','الشم','الدهان'],['راقب جهة واحدة','بلل القطب','احتياطات مماثلة بالجهة الأخرى','أغلق الغرفة']]},
{t:['آگ کے خطرے ہٹائیں','extinguisher تیار','fire watch مقرر','دوسری طرف چیک','cylinders/hoses قابو','gas باہر بند','container محفوظ','رکیں اور alarm'],x:['hot work محفوظ مقام لے جائیں یا combustibles ہٹا کر sparks/heat/slag روکیں۔ flammable coating یا heavy dust میں کام نہیں۔','2A فی 3000 ft² اور زیادہ سے زیادہ 100 ft travel؛ 5 gal liquid یا 5 lb gas سے زیادہ پر 10B 50 ft کے اندر تیار ہو۔','عام controls ناکافی ہوں تو دوران اور بعد اتنی دیر watch کہ آگ کا امکان نہ رہے۔ OSHA کا universal 30/60 minute نہیں۔ hazard، alarm، exit، extinguisher جانے۔','walls/floor/ceiling کی دوسری جانب بھی وہی controls؛ voids، openings، lower levels چیک کریں۔','cylinders upright secure؛ oxygen/fuel 20 ft یا 5-ft noncombustible 30-min barrier۔ oxygen سے oil/grease دور۔','torch unattended ہو تو gas enclosed space کے باہر بند؛ shift/night پر torch/hose باہر؛ disconnected open hoses فوراً باہر۔','flammable container بند۔ سابق toxic/flammable drum کو water fill یا clean/ventilate/test اور heating سے پہلے pressure vent دیں۔','dust، gas smell، leak، missing extinguisher، uncontrolled sparks یا unsafe opposite side پر رکیں۔ alarm دیں؛ escape safe ہو تو ہی extinguisher۔'],q:['universal fire-watch period؟','2A تک max travel؟','oxygen/fuel separation؟','flammable drum پر hot work کب؟','spark wall پار کرے؟'],a:[['30 min','60','90','fixed نہیں؛ امکان ختم ہونے تک'],['25','50','100','150'],['20 ft یا specified 5-ft barrier','5 only','10/wood','none'],['lid open','clean/vent/test یا water plus vent','smell','paint'],['ایک side','electrode wet','دوسری طرف برابر controls','room close']]},
{t:['आग खतरे हटाएँ','extinguisher तैयार','fire watch नियुक्त','दूसरी तरफ जाँच','cylinder/hose नियंत्रण','gas बाहर बंद','container सुरक्षित','रोकें और alarm'],x:['hot work सुरक्षित जगह ले जाएँ या combustibles हटाकर sparks/heat/slag रोकें। flammable coating या heavy dust में काम नहीं।','2A प्रति 3000 ft² और अधिकतम 100 ft travel; 5 gal liquid या 5 lb gas से अधिक पर 10B 50 ft में तैयार।','सामान्य नियंत्रण पर्याप्त न हों तो दौरान और बाद इतनी देर watch कि आग की संभावना न रहे। OSHA universal 30/60 minute नहीं। hazard, alarm, exit और extinguisher जाने।','wall/floor/ceiling के दूसरी ओर भी समान नियंत्रण; void, opening और नीचे स्तर जाँचें।','cylinder upright secure; oxygen/fuel 20 ft या 5-ft noncombustible 30-min barrier। oxygen से oil/grease दूर।','torch unattended हो तो gas enclosed space के बाहर बंद; shift/night पर torch/hose बाहर; खुले disconnected hose तुरंत बाहर।','flammable container बंद। पुराने toxic/flammable drum को water fill या clean/ventilate/test करें और heating से पहले pressure vent दें।','dust, gas smell, leak, missing extinguisher, uncontrolled sparks या unsafe opposite side पर रोकें। alarm दें; escape सुरक्षित हो तभी extinguisher।'],q:['universal fire-watch अवधि?','2A तक max travel?','oxygen/fuel separation?','flammable drum पर hot work कब?','spark wall पार करे?'],a:[['30 min','60','90','fixed नहीं; संभावना खत्म तक'],['25','50','100','150'],['20 ft या specified 5-ft barrier','5 only','10/wood','none'],['lid open','clean/vent/test या water plus vent','smell','paint'],['एक side','electrode wet','दूसरी तरफ समान controls','room बंद']]});

const compact=(title:string,refs:string[],facts:string[],correct=[1,2,0,3,1]):Record<CourseLanguage,CourseLesson>=>{
 const labels={ar:['القاعدة','القياس','الشخص المسؤول','طريقة العمل','الفحص','منطقة الخطر','الإيقاف','تذكر'],ur:['اصول','پیمائش','ذمہ دار شخص','محفوظ طریقہ','معائنہ','خطرہ زون','کام روکیں','یاد رکھیں'],hi:['नियम','माप','जिम्मेदार व्यक्ति','सुरक्षित विधि','निरीक्षण','खतरा क्षेत्र','काम रोकें','याद रखें']};
 const prefix={ar:'تدريب عملي: ',ur:'عملی تربیت: ',hi:'व्यावहारिक प्रशिक्षण: '};
 const qs:any={
  en:[['What must control the work?',['Guesswork','The cited OSHA rule and site hazard assessment','PPE alone','Production target']],['Who verifies changing conditions?',['Visitor','Any passer-by','The designated competent/authorized person for the task','Driver']],['When must work stop?',['When a required control fails','Only after injury','At lunch only','When the job is nearly done']],['May a site rule be more protective than OSHA minimum?',['Never','Only verbally','Only at night','Yes']],['What should a worker do before starting?',['Begin and ask later','Understand the hazards, controls and stop-work triggers','Rely on memory only','Remove warnings']]],
  ar:[['ما الذي يحكم العمل؟',['التخمين','نص OSHA وتقييم مخاطر الموقع','PPE وحده','هدف الإنتاج']],['من يتحقق من تغير الظروف؟',['زائر','أي عابر','الشخص المختص/المصرح للمهمة','السائق']],['متى يتوقف العمل؟',['عند فشل ضابط مطلوب','بعد إصابة فقط','وقت الغداء','قرب النهاية']],['هل يمكن لقاعدة الموقع أن تكون أشد حماية؟',['أبداً','شفهياً فقط','ليلاً فقط','نعم']],['ماذا يفعل العامل قبل البدء؟',['يبدأ ثم يسأل','يفهم الأخطار والضوابط وأسباب الإيقاف','يعتمد الذاكرة','يزيل التحذير']]],
  ur:[['کام کس کے مطابق؟',['اندازہ','OSHA rule اور site hazard assessment','صرف PPE','production target']],['بدلتے حالات کون verify کرے؟',['visitor','کوئی بھی','task کا competent/authorized person','driver']],['کام کب رکے؟',['required control fail پر','صرف injury بعد','lunch پر','اختتام قریب']],['site rule OSHA minimum سے زیادہ protective ہو سکتا؟',['نہیں','صرف زبانی','صرف رات','ہاں']],['شروع سے پہلے worker؟',['شروع پھر پوچھے','hazards, controls, stop triggers سمجھے','صرف memory','warning ہٹائے']]],
  hi:[['काम किसके अनुसार?',['अनुमान','OSHA rule और site hazard assessment','केवल PPE','production target']],['बदलती दशा कौन सत्यापित करे?',['visitor','कोई भी','task का competent/authorized person','driver']],['काम कब रोके?',['required control fail पर','केवल injury बाद','lunch पर','अंत निकट']],['site rule OSHA minimum से अधिक protective हो सकता?',['नहीं','केवल मौखिक','केवल रात','हाँ']],['शुरू से पहले worker?',['शुरू फिर पूछे','hazards, controls, stop triggers समझे','केवल memory','warning हटाए']]]};
 const base:any={}; for(const lang of ['en','ar','ur','hi'] as CourseLanguage[]){base[lang]={slides:facts.map((x,i)=>({n:String(i+1).padStart(2,'0'),title:lang==='en'?`${title}: ${['rule','measure','responsibility','safe method','inspection','danger zone','stop work','memory check'][i]}`:labels[lang as 'ar'][i],text:lang==='en'?x:prefix[lang as 'ar']+x,ref:refs[i]})),quiz:qs[lang].map((z:any,i:number)=>({q:z[0],a:z[1],correct:correct[i]}))};} return base;
};

export const housekeepingCourse=compact('Housekeeping & FOD',Array(8).fill('29 CFR 1926.25; 1926.252'),[
'Keep work areas, passageways and stairs clear of scrap, protruding nails, loose materials, cords and spills. Remove combustible scrap and debris at regular intervals; do not wait for shift end when accumulation creates a hazard.',
'Use covered containers for oily or hazardous waste. When dropping material more than 20 ft outside a building, use an enclosed chute. Guard a floor/opening used for disposal with a barricade at least 42 in high and post warning signs.',
'Assign ownership by zone and shift. Supervisors inspect; every worker controls tools, fasteners, packaging and personal items. FOD is an industry control concept: OSHA does not prescribe one universal FOD count or zone size.',
'Inventory small items before and after work, cap open pipes, cover intakes, tether tools where falling-object assessment requires, segregate waste and use magnets/screens/vacuums suited to the material. Never use compressed air in a way that spreads contamination or exposes workers.',
'Inspect access routes continuously and after deliveries, weather and work changes. Record missing tools or parts and search before energizing, closing equipment, concrete placement or turnover. A clean-looking area can still contain hidden FOD.',
'Establish red zones below overhead work and around sensitive equipment. Secure materials against wind and vibration. Do not throw material freely; use chutes, hoists or controlled lowering and protect workers below.',
'Stop for blocked exit, unstable stack, sharp scrap, spill, missing tool, open component, uncontrolled waste drop or combustible accumulation. Isolate the area, correct the cause and report any item that may have entered equipment.',
'Memory rule: clean as you go, count what enters, count what leaves, protect openings, and verify before close-up. Housekeeping prevents slips, fire, struck-by events and equipment damage; it is a production control, not decoration.'
]);

export const excavationCourse=compact('Excavation & Trenching',Array(8).fill('29 CFR 1926.650–1926.652; Subpart P Apps A–F'),[
'A competent person who can identify hazards and promptly correct them classifies soil and selects/monitors controls. A trench is a narrow excavation no wider than 15 ft at its bottom. Locate underground utilities before digging and protect them while exposed.',
'Protect workers from cave-in at 5 ft (1.52 m) or deeper unless entirely stable rock; below 5 ft a competent person may determine no cave-in hazard exists. Excavations deeper than 20 ft require a protective system designed or approved by a registered professional engineer.',
'Use sloping, benching, shoring or shielding selected from the standard, tabulated data or engineered design. Maximum simple slopes are Type A 3/4H:1V, Type B 1H:1V and Type C 1.5H:1V; layered, fissured or previously disturbed soil may force a weaker classification.',
'For trenches 4 ft (1.22 m) or deeper, provide ladder, stair, ramp or other safe egress so no worker travels more than 25 ft (7.62 m) laterally. Ladders must be secured and extend as required for safe access; never climb shoring or a trench box.',
'Keep spoil, equipment and materials at least 2 ft (0.61 m) from the edge or use retaining devices. Protect workers from traffic with high-visibility garments and controls; keep them out from under loads handled by lifting/digging equipment.',
'Test atmospheres in excavations over 4 ft deep where oxygen deficiency or hazardous atmosphere could reasonably exist. Provide ventilation or respiratory protection as required, rescue equipment, and do not allow water accumulation without competent-person-controlled precautions.',
'The competent person inspects daily before work, as needed during the shift, and after rainstorms or other hazard-increasing events. Workers leave immediately for cracks, sloughing, bulging/heaving bottom, water, protective-system movement, vibration damage or atmospheric alarm.',
'A trench box protects only workers inside its protected area; never remain inside while it is installed, removed or moved vertically. Excavation may extend up to 2 ft below a shield only when designed for full depth and soil loss is not indicated.'
],[1,2,0,3,1]);

export const electricalCourse=compact('Electrical Safety',Array(8).fill('29 CFR 1926 Subpart K; 1926.403–1926.417'),[
'Only qualified persons work on energized parts. Deenergize, lock/tag and verify whenever feasible. Guard live parts operating at 50 volts or more against accidental contact by enclosure, location, partition or elevation; treat damaged insulation as energized exposure.',
'On construction sites protect 120-V, single-phase, 15- and 20-amp receptacles not part of permanent wiring with GFCIs or a written assured equipment grounding conductor program. The program is not a casual substitute: it requires a designated person, inspections, tests and records.',
'Under an assured grounding program, visually inspect cord sets and plug-connected equipment before each day’s use. Test grounding continuity and correct terminal connection before first use, after repair, after suspected damage, and at intervals not over 3 months (6 months for fixed, nonexposed cords).',
'Use flexible cords only for permitted temporary purposes. Protect from sharp edges and damage; do not run through holes, doors, windows or attach to building surfaces in prohibited ways. Never lift equipment by its cord or remove the grounding pin.',
'Temporary lights need guards where bulbs may be struck; metal-shell lampholders must be grounded. Keep wet-location equipment approved for the location, hands dry, and connections elevated/protected. A GFCI reduces shock risk but does not make unsafe work acceptable.',
'Maintain required approach distance from overhead lines and have the utility deenergize/ground or use specified guarding. For cranes, covered equipment normally stays at least 10 ft from lines up to 50 kV; use the applicable larger distance at higher voltage.',
'Inspect panels, cords, tools and GFCIs before use. Close unused openings, label circuits, maintain working clearance and use rated covers. Stop for missing ground, exposed conductor, heat, odor, arcing, tripping GFCI, water entry or an unidentified supply.',
'In an electrical contact, do not touch the person or equipment until energy is isolated. Call emergency help, use trained rescue/CPR response and suitable nonconductive methods only within training. Report and quarantine involved equipment before reuse.'
]);

export const lotoCourse=compact('Lockout/Tagout',Array(8).fill('29 CFR 1926.417; 29 CFR 1910.147 where applicable'),[
'Before work on circuits or equipment, identify every electrical, mechanical, hydraulic, pneumatic, chemical, thermal, gravity and stored-energy source. Notify affected employees and use the energy-control procedure applicable to the equipment—not just the stop button.',
'Controls of deenergized electrical equipment must be tagged, and circuits must be rendered inoperative. Tags identify the equipment/circuit and warn against operation. Where a lock can be applied under the applicable energy-control rule, use each authorized employee’s personal lock.',
'Authorized employees apply lockout and perform servicing; affected employees operate/use the machine or work nearby; other employees must not restart or tamper. Affected and other employees receive role-appropriate instruction; only authorized employees execute energy isolation.',
'Shut down normally, isolate every source, apply locks/tags, release or restrain stored energy, and verify isolation. Block raised parts, discharge capacitors, bleed pressure, restrain springs and address reaccumulation. Pressing start is only one part of verification.',
'Before work, an authorized employee verifies zero-energy condition with properly rated/tested instruments and attempts normal controls safely. For electrical testing, test the meter on a known source before and after (live-dead-live) under the employer’s safe-work procedure.',
'For group lockout, each authorized worker applies a personal lock or equivalent control to the group device and remains protected during shift changes. The primary authorized employee coordinates scope, status and handover; never share one anonymous lock.',
'Normally only the employee who applied a lock removes it. An employer exception requires a specific documented procedure, verification the employee is absent, reasonable contact efforts, and informing that employee before resuming work. Never cut a lock for convenience.',
'Before reenergizing, inspect the area, remove tools, replace guards, confirm people are clear, remove devices by authorized procedure and notify affected employees. Stop for unidentified energy, missing isolation point, failed test, changed scope or a person whose protection is uncertain.'
]);

