import type { CourseLanguage, CourseLesson } from './course-catalog';

export const incidentInvestigationCourse: Record<CourseLanguage | 'bn', CourseLesson> = {
  en: {
    slides: [
      { n: '01', title: 'Report incidents and near misses promptly', text: 'An incident is an unplanned event that caused or could have caused injury, illness, property damage or environmental harm. Get emergency help first, then notify the supervisor and project HSE team without delay. Reporting must be easy, accurate and free from retaliation.', ref: '29 CFR 1904.35; OSHA Incident Investigation' },
      { n: '02', title: 'Make the scene safe and preserve evidence', text: 'Complete rescue and medical response before investigating. Stop work, control immediate hazards, isolate hazardous energy only when trained and authorized, and barricade the area. Do not move equipment or disturb evidence except to rescue someone or prevent further harm.', ref: 'OSHA Incident Investigation: A Guide for Employers, Steps 1–2' },
      { n: '03', title: 'Use a trained, balanced investigation team', text: 'Assign a responsible lead and include managers and workers who understand the task. Add HSE, technical or specialist support when needed. Define who investigates, what information is required, who approves actions and when each action is due.', ref: 'OSHA Incident Investigation Overview; OSHA Recommended Practices' },
      { n: '04', title: 'Collect facts before forming conclusions', text: 'Record the date, time, location and conditions. Photograph and sketch the scene; note positions and measurements; preserve relevant equipment; and review permits, risk assessments, procedures, training, inspections, maintenance, SDS and environmental data. Separate verified facts from assumptions.', ref: 'OSHA Incident Investigation: A Guide for Employers, Appendices B–E' },
      { n: '05', title: 'Interview without blame', text: 'Interview involved people and witnesses promptly and separately in a suitable place. Explain that the goal is prevention, ask open questions such as “What happened next?”, listen without interruption, confirm the account and use a competent interpreter when needed. Never intimidate or suggest answers.', ref: 'OSHA Incident Investigation: A Guide for Employers, Collect Information' },
      { n: '06', title: 'Find direct, contributing and root causes', text: 'Look beyond “worker error.” Examine equipment, materials, environment, procedures, supervision, workload, training, maintenance and management-system weaknesses. Use evidence and tools such as the 5 Whys or a cause-and-effect diagram, then test whether the identified causes explain the event.', ref: 'OSHA Incident Investigation Overview; OSHA 3895' },
      { n: '07', title: 'Choose stronger corrective actions first', text: 'Control each verified cause using the hierarchy: eliminate the hazard, substitute a safer option, apply engineering controls, then administrative or work-practice controls, and PPE. Assign an owner, priority and due date. Keep effective temporary controls until permanent actions are complete.', ref: 'OSHA Recommended Practices: Hazard Prevention and Control' },
      { n: '08', title: 'Complete incident reporting and verify closure', text: 'Report every incident and near miss promptly through the project incident-reporting process. Notify the supervisor and project HSE team, and immediately escalate serious events as required by TDC, the client, the project and applicable Saudi requirements. Record the facts, causes, actions, owners and deadlines, share relevant lessons, and verify that corrective actions are effective before closure.', ref: 'TDC, client and project incident-reporting procedures; applicable Saudi requirements' },
    ],
    quiz: [
      { q: 'What is the correct first response after an incident?', a: ['Begin witness interviews immediately', 'Provide emergency care, control immediate danger and report the event', 'Move all equipment to clear the area', 'Decide who is at fault'], correct: 1 },
      { q: 'What is the correct way to report an incident or near miss?', a: ['Report only when someone is injured', 'Wait until the next weekly meeting', 'Report promptly to the supervisor and project HSE team, then follow TDC, client, project and applicable Saudi requirements', 'Wait until the investigation is complete'], correct: 2 },
      { q: 'Which witness-interview method best supports a reliable investigation?', a: ['Interview separately, ask open questions and avoid blame', 'Interview everyone together and seek agreement', 'Tell the witness the expected answer', 'Wait until corrective actions are complete'], correct: 0 },
      { q: 'Which finding is a root cause rather than only an immediate cause?', a: ['The employee slipped', 'A guard was missing', 'The tool contacted the hand', 'The inspection system repeatedly failed to identify and correct missing guards'], correct: 3 },
      { q: 'Which corrective-action plan is strongest?', a: ['Issue a reminder and close the case immediately', 'Eliminate or engineer out the hazard where feasible, assign an owner and due date, then verify effectiveness', 'Rely only on PPE for every hazard', 'Reopen work before controls are installed'], correct: 1 },
    ],
  },
  ar: {
    slides: [
      { n: '01', title: 'أبلغ فوراً عن الحوادث والحوادث الوشيكة', text: 'الحادث حدث غير مخطط تسبب أو كان يمكن أن يتسبب في إصابة أو مرض أو ضرر للممتلكات أو البيئة. اطلب المساعدة الطارئة أولاً، ثم أخطر المشرف وفريق HSE بالمشروع دون تأخير. يجب أن يكون الإبلاغ سهلاً ودقيقاً ومن دون انتقام.', ref: '29 CFR 1904.35; OSHA Incident Investigation' },
      { n: '02', title: 'أمّن الموقع واحفظ الأدلة', text: 'أكمل الإنقاذ والاستجابة الطبية قبل التحقيق. أوقف العمل وسيطر على الأخطار الفورية واعزل الطاقة الخطرة فقط إذا كنت مدرباً ومصرحاً لك، وضع حواجز حول المنطقة. لا تحرك المعدات أو تعبث بالأدلة إلا لإنقاذ شخص أو منع ضرر إضافي.', ref: 'OSHA Incident Investigation: A Guide for Employers, Steps 1–2' },
      { n: '03', title: 'استخدم فريق تحقيق مدرباً ومتوازناً', text: 'عيّن قائداً مسؤولاً وأشرك مديرين وعمالاً يفهمون المهمة. أضف دعم HSE أو الدعم الفني أو المتخصص عند الحاجة. حدد من يحقق، والمعلومات المطلوبة، ومن يعتمد الإجراءات، وموعد استحقاق كل إجراء.', ref: 'OSHA Incident Investigation Overview; OSHA Recommended Practices' },
      { n: '04', title: 'اجمع الحقائق قبل الاستنتاج', text: 'سجل التاريخ والوقت والموقع والظروف. صوّر الموقع وارسمه، وسجل المواقع والقياسات، واحفظ المعدات المهمة، وراجع التصاريح وتقييمات المخاطر والإجراءات والتدريب والتفتيش والصيانة وSDS والبيانات البيئية. افصل الحقائق المثبتة عن الافتراضات.', ref: 'OSHA Incident Investigation: A Guide for Employers, Appendices B–E' },
      { n: '05', title: 'أجرِ المقابلة دون لوم', text: 'قابل الأشخاص المعنيين والشهود سريعاً وبشكل منفصل في مكان مناسب. وضح أن الهدف هو الوقاية، واسأل أسئلة مفتوحة مثل «ماذا حدث بعد ذلك؟»، واستمع دون مقاطعة، وأكد الرواية واستخدم مترجماً كفؤاً عند الحاجة. لا ترهب أحداً ولا تقترح إجابات.', ref: 'OSHA Incident Investigation: A Guide for Employers, Collect Information' },
      { n: '06', title: 'حدد الأسباب المباشرة والمساهمة والجذرية', text: 'انظر إلى ما هو أبعد من «خطأ العامل». افحص المعدات والمواد والبيئة والإجراءات والإشراف وعبء العمل والتدريب والصيانة ونقاط ضعف نظام الإدارة. استخدم الأدلة وأدوات مثل لماذا خمس مرات أو مخطط السبب والنتيجة، ثم تحقق من أن الأسباب تفسر الحدث.', ref: 'OSHA Incident Investigation Overview; OSHA 3895' },
      { n: '07', title: 'اختر إجراءات تصحيحية أقوى أولاً', text: 'سيطر على كل سبب مؤكد حسب التسلسل الهرمي: إزالة الخطر، الاستبدال بخيار أكثر أماناً، الضوابط الهندسية، ثم الضوابط الإدارية أو ممارسات العمل، وأخيراً PPE. عيّن مسؤولاً وأولوية وموعداً نهائياً، وأبقِ الضوابط المؤقتة الفعالة حتى اكتمال الحل الدائم.', ref: 'OSHA Recommended Practices: Hazard Prevention and Control' },
      { n: '08', title: 'أكمل الإبلاغ عن الحادث وتحقق من الإغلاق', text: 'أبلغ فوراً عن كل حادث وحادث وشيك من خلال نظام الإبلاغ بالمشروع. أخطر المشرف وفريق HSE بالمشروع، وصعّد الأحداث الخطيرة فوراً وفق متطلبات TDC والعميل والمشروع والمتطلبات السعودية المعمول بها. سجل الحقائق والأسباب والإجراءات والمسؤولين والمواعيد، وشارك الدروس المهمة، وتحقق من فعالية الإجراءات التصحيحية قبل الإغلاق.', ref: 'إجراءات الإبلاغ عن الحوادث لدى TDC والعميل والمشروع؛ المتطلبات السعودية المعمول بها' },
    ],
    quiz: [
      { q: 'ما الاستجابة الأولى الصحيحة بعد الحادث؟', a: ['ابدأ مقابلة الشهود فوراً', 'قدم الرعاية الطارئة وسيطر على الخطر الفوري وأبلغ عن الحدث', 'انقل جميع المعدات لإخلاء الموقع', 'حدد المخطئ'], correct: 1 },
      { q: 'ما الطريقة الصحيحة للإبلاغ عن حادث أو حادث وشيك؟', a: ['الإبلاغ فقط عند وقوع إصابة', 'الانتظار حتى الاجتماع الأسبوعي التالي', 'الإبلاغ فوراً إلى المشرف وفريق HSE بالمشروع ثم اتباع متطلبات TDC والعميل والمشروع والمتطلبات السعودية المعمول بها', 'الانتظار حتى اكتمال التحقيق'], correct: 2 },
      { q: 'أي طريقة لمقابلة الشهود تدعم تحقيقاً موثوقاً؟', a: ['مقابلة كل شخص منفرداً بأسئلة مفتوحة ودون لوم', 'جمع الجميع والسعي لاتفاقهم', 'إخبار الشاهد بالإجابة المتوقعة', 'الانتظار حتى انتهاء الإجراءات التصحيحية'], correct: 0 },
      { q: 'أي نتيجة تمثل سبباً جذرياً لا سبباً مباشراً فقط؟', a: ['انزلق العامل', 'كان الواقي مفقوداً', 'لامست الأداة اليد', 'فشل نظام التفتيش مراراً في اكتشاف الواقيات المفقودة وتصحيحها'], correct: 3 },
      { q: 'أي خطة إجراءات تصحيحية هي الأقوى؟', a: ['إصدار تذكير وإغلاق القضية فوراً', 'إزالة الخطر أو ضبطه هندسياً حيث يمكن، وتعيين مسؤول وموعد، ثم التحقق من الفعالية', 'الاعتماد على PPE فقط لكل خطر', 'إعادة العمل قبل تركيب الضوابط'], correct: 1 },
    ],
  },
  ur: {
    slides: [
      { n: '01', title: 'واقعات اور قریب الوقوع واقعات فوراً رپورٹ کریں', text: 'واقعہ ایک غیر منصوبہ بند واقعہ ہے جس سے چوٹ، بیماری، املاک یا ماحول کو نقصان ہوا یا ہو سکتا تھا۔ پہلے ہنگامی مدد لیں، پھر سپروائزر اور پروجیکٹ HSE ٹیم کو بلا تاخیر اطلاع دیں۔ رپورٹنگ آسان، درست اور انتقامی کارروائی سے پاک ہونی چاہیے۔', ref: '29 CFR 1904.35; OSHA Incident Investigation' },
      { n: '02', title: 'جگہ محفوظ کریں اور ثبوت بچائیں', text: 'تحقیق سے پہلے ریسکیو اور طبی مدد مکمل کریں۔ کام روکیں، فوری خطرات قابو کریں، خطرناک توانائی صرف تربیت یافتہ اور مجاز ہونے پر isolate کریں، اور علاقہ barricade کریں۔ کسی کو بچانے یا مزید نقصان روکنے کے سوا سامان یا ثبوت نہ چھیڑیں۔', ref: 'OSHA Incident Investigation: A Guide for Employers, Steps 1–2' },
      { n: '03', title: 'تربیت یافتہ متوازن تحقیقاتی ٹیم بنائیں', text: 'ایک ذمہ دار لیڈ مقرر کریں اور کام جاننے والے مینیجرز اور کارکن شامل کریں۔ ضرورت کے مطابق HSE، تکنیکی یا ماہر مدد لیں۔ طے کریں کون تحقیق کرے گا، کون سی معلومات درکار ہیں، کارروائی کون منظور کرے گا اور ہر کام کب مکمل ہوگا۔', ref: 'OSHA Incident Investigation Overview; OSHA Recommended Practices' },
      { n: '04', title: 'نتیجہ نکالنے سے پہلے حقائق جمع کریں', text: 'تاریخ، وقت، مقام اور حالات درج کریں۔ تصاویر اور خاکہ بنائیں، پوزیشن اور پیمائش نوٹ کریں، متعلقہ سامان محفوظ کریں، اور permits، Risk Assessments، طریقہ کار، تربیت، معائنہ، maintenance، SDS اور ماحولیاتی ڈیٹا دیکھیں۔ ثابت شدہ حقائق کو اندازوں سے الگ رکھیں۔', ref: 'OSHA Incident Investigation: A Guide for Employers, Appendices B–E' },
      { n: '05', title: 'الزام کے بغیر انٹرویو کریں', text: 'متاثرہ افراد اور گواہوں سے جلد، الگ الگ اور مناسب جگہ پر بات کریں۔ واضح کریں کہ مقصد روک تھام ہے، “اس کے بعد کیا ہوا؟” جیسے کھلے سوال پوچھیں، بغیر مداخلت سنیں، بیان کی تصدیق کریں اور ضرورت پر قابل مترجم دیں۔ دھمکائیں نہیں اور جواب نہ سجھائیں۔', ref: 'OSHA Incident Investigation: A Guide for Employers, Collect Information' },
      { n: '06', title: 'فوری، معاون اور بنیادی وجوہات تلاش کریں', text: 'صرف “کارکن کی غلطی” پر نہ رکیں۔ سامان، مواد، ماحول، طریقہ کار، نگرانی، کام کا دباؤ، تربیت، maintenance اور management system کی کمزوریاں دیکھیں۔ ثبوت کے ساتھ 5 Whys یا cause-and-effect diagram استعمال کریں، پھر جانچیں کہ وجوہات واقعہ کی وضاحت کرتی ہیں۔', ref: 'OSHA Incident Investigation Overview; OSHA 3895' },
      { n: '07', title: 'پہلے مضبوط اصلاحی اقدامات منتخب کریں', text: 'ہر ثابت شدہ وجہ کو hierarchy کے مطابق قابو کریں: خطرہ ختم کریں، کم خطرناک متبادل، engineering controls، پھر administrative/work-practice controls، اور PPE۔ ذمہ دار شخص، ترجیح اور آخری تاریخ مقرر کریں؛ مستقل حل تک مؤثر عارضی controls برقرار رکھیں۔', ref: 'OSHA Recommended Practices: Hazard Prevention and Control' },
      { n: '08', title: 'واقعے کی رپورٹنگ مکمل کریں اور بندش کی تصدیق کریں', text: 'ہر واقعہ اور قریب الوقوع واقعہ project incident-reporting process کے ذریعے فوراً رپورٹ کریں۔ supervisor اور project HSE team کو اطلاع دیں، اور سنگین واقعات کو TDC، client، project اور قابل اطلاق سعودی تقاضوں کے مطابق فوری escalate کریں۔ حقائق، وجوہات، اقدامات، ذمہ دار افراد اور تاریخیں درج کریں، اہم سبق شیئر کریں، اور بند کرنے سے پہلے اصلاحی اقدامات کی مؤثریت جانچیں۔', ref: 'TDC، client اور project incident-reporting procedures؛ قابل اطلاق سعودی تقاضے' },
    ],
    quiz: [
      { q: 'واقعے کے بعد درست پہلا ردعمل کیا ہے؟', a: ['فوراً گواہوں کے انٹرویو شروع کریں', 'ہنگامی نگہداشت دیں، فوری خطرہ قابو کریں اور واقعہ رپورٹ کریں', 'تمام سامان ہٹا دیں', 'قصوروار طے کریں'], correct: 1 },
      { q: 'کسی واقعے یا قریب الوقوع واقعے کی درست رپورٹنگ کیا ہے؟', a: ['صرف چوٹ لگنے پر رپورٹ کریں', 'اگلی ہفتہ وار میٹنگ تک انتظار کریں', 'فوراً supervisor اور project HSE team کو رپورٹ کریں، پھر TDC، client، project اور قابل اطلاق سعودی تقاضے پورے کریں', 'تحقیق مکمل ہونے تک انتظار کریں'], correct: 2 },
      { q: 'قابل اعتماد گواہ انٹرویو کا بہترین طریقہ کیا ہے؟', a: ['الگ انٹرویو، کھلے سوال اور الزام سے گریز', 'سب کو ساتھ بٹھا کر اتفاق لیں', 'متوقع جواب بتائیں', 'اصلاحی کام کے بعد انتظار کریں'], correct: 0 },
      { q: 'کون سا نتیجہ صرف فوری نہیں بلکہ بنیادی وجہ ہے؟', a: ['کارکن پھسل گیا', 'گارڈ غائب تھا', 'ٹول ہاتھ سے ٹکرایا', 'معائنہ نظام بار بار غائب guards تلاش اور درست نہ کر سکا'], correct: 3 },
      { q: 'کون سا اصلاحی منصوبہ سب سے مضبوط ہے؟', a: ['یاددہانی دے کر کیس فوراً بند کریں', 'جہاں ممکن ہو خطرہ ختم یا engineer out کریں، مالک اور تاریخ دیں، پھر مؤثریت جانچیں', 'ہر خطرے کے لیے صرف PPE', 'controls سے پہلے کام کھولیں'], correct: 1 },
    ],
  },
  hi: {
    slides: [
      { n: '01', title: 'घटनाओं और निकट-चूकों की तुरंत रिपोर्ट करें', text: 'घटना एक अनियोजित घटना है जिससे चोट, बीमारी, संपत्ति या पर्यावरण को हानि हुई या हो सकती थी। पहले आपात सहायता लें, फिर पर्यवेक्षक और परियोजना HSE टीम को बिना देर बताएँ। रिपोर्टिंग आसान, सही और प्रतिशोध से मुक्त होनी चाहिए।', ref: '29 CFR 1904.35; OSHA Incident Investigation' },
      { n: '02', title: 'स्थल सुरक्षित करें और साक्ष्य बचाएँ', text: 'जाँच से पहले बचाव और चिकित्सा प्रतिक्रिया पूरी करें। काम रोकें, तत्काल खतरे नियंत्रित करें, खतरनाक ऊर्जा केवल प्रशिक्षित और अधिकृत होने पर अलग करें और क्षेत्र को अवरोधित करें। किसी को बचाने या आगे की हानि रोकने के अलावा उपकरण या साक्ष्य न हटाएँ।', ref: 'OSHA Incident Investigation: A Guide for Employers, Steps 1–2' },
      { n: '03', title: 'प्रशिक्षित और संतुलित जाँच दल बनाएँ', text: 'एक जिम्मेदार प्रमुख नियुक्त करें और कार्य समझने वाले प्रबंधक व कर्मचारी शामिल करें। आवश्यकता पर HSE, तकनीकी या विशेषज्ञ सहायता लें। तय करें कि कौन जाँच करेगा, कौन-सी जानकारी चाहिए, कार्रवाई कौन मंजूर करेगा और हर कार्रवाई कब पूरी होगी।', ref: 'OSHA Incident Investigation Overview; OSHA Recommended Practices' },
      { n: '04', title: 'निष्कर्ष से पहले तथ्य जुटाएँ', text: 'दिनांक, समय, स्थान और दशाएँ लिखें। फोटो और रेखाचित्र लें, स्थिति और माप दर्ज करें, संबंधित उपकरण सुरक्षित रखें तथा permits, Risk Assessments, प्रक्रियाएँ, प्रशिक्षण, निरीक्षण, maintenance, SDS और पर्यावरण डेटा देखें। सत्यापित तथ्यों को अनुमान से अलग रखें।', ref: 'OSHA Incident Investigation: A Guide for Employers, Appendices B–E' },
      { n: '05', title: 'बिना दोष लगाए साक्षात्कार करें', text: 'संबंधित लोगों और गवाहों का शीघ्र, अलग-अलग और उपयुक्त जगह साक्षात्कार करें। बताएँ कि लक्ष्य रोकथाम है, “आगे क्या हुआ?” जैसे खुले प्रश्न पूछें, बिना टोके सुनें, विवरण की पुष्टि करें और आवश्यकता पर सक्षम दुभाषिया दें। डराएँ नहीं और उत्तर न सुझाएँ।', ref: 'OSHA Incident Investigation: A Guide for Employers, Collect Information' },
      { n: '06', title: 'प्रत्यक्ष, सहायक और मूल कारण खोजें', text: 'केवल “कर्मचारी की गलती” पर न रुकें। उपकरण, सामग्री, वातावरण, प्रक्रिया, पर्यवेक्षण, काम का दबाव, प्रशिक्षण, maintenance और प्रबंधन-प्रणाली की कमजोरियाँ देखें। साक्ष्य के साथ 5 Whys या कारण-प्रभाव आरेख अपनाएँ, फिर जाँचें कि कारण घटना समझाते हैं।', ref: 'OSHA Incident Investigation Overview; OSHA 3895' },
      { n: '07', title: 'पहले अधिक मजबूत सुधार चुनें', text: 'हर पुष्ट कारण को पदानुक्रम से नियंत्रित करें: खतरा हटाएँ, सुरक्षित विकल्प अपनाएँ, engineering controls लगाएँ, फिर administrative/work-practice controls और PPE। जिम्मेदार व्यक्ति, प्राथमिकता और अंतिम तिथि तय करें; स्थायी समाधान तक प्रभावी अस्थायी नियंत्रण रखें।', ref: 'OSHA Recommended Practices: Hazard Prevention and Control' },
      { n: '08', title: 'घटना रिपोर्टिंग पूरी करें और समापन सत्यापित करें', text: 'हर घटना और निकट-चूक को परियोजना की incident-reporting प्रक्रिया से तुरंत रिपोर्ट करें। पर्यवेक्षक और परियोजना HSE टीम को सूचित करें तथा गंभीर घटनाओं को TDC, client, project और लागू सऊदी आवश्यकताओं के अनुसार तुरंत आगे बढ़ाएँ। तथ्य, कारण, कार्रवाई, जिम्मेदार व्यक्ति और समय-सीमा दर्ज करें, जरूरी सीख साझा करें और बंद करने से पहले सुधारों की प्रभावशीलता जाँचें।', ref: 'TDC, client और project incident-reporting प्रक्रियाएँ; लागू सऊदी आवश्यकताएँ' },
    ],
    quiz: [
      { q: 'घटना के बाद सही पहली प्रतिक्रिया क्या है?', a: ['तुरंत गवाहों का साक्षात्कार शुरू करें', 'आपात देखभाल दें, तत्काल खतरा नियंत्रित करें और घटना रिपोर्ट करें', 'सभी उपकरण हटा दें', 'दोषी तय करें'], correct: 1 },
      { q: 'घटना या निकट-चूक की सही रिपोर्टिंग क्या है?', a: ['केवल चोट होने पर रिपोर्ट करना', 'अगली साप्ताहिक बैठक तक प्रतीक्षा करना', 'तुरंत पर्यवेक्षक और परियोजना HSE टीम को रिपोर्ट करना, फिर TDC, client, project और लागू सऊदी आवश्यकताओं का पालन करना', 'जाँच पूरी होने तक प्रतीक्षा करना'], correct: 2 },
      { q: 'विश्वसनीय गवाह साक्षात्कार की सर्वोत्तम विधि क्या है?', a: ['अलग साक्षात्कार, खुले प्रश्न और दोष से बचाव', 'सबको साथ रखकर सहमति लें', 'अपेक्षित उत्तर बताएँ', 'सुधार पूरे होने तक प्रतीक्षा करें'], correct: 0 },
      { q: 'कौन-सा निष्कर्ष केवल तात्कालिक नहीं बल्कि मूल कारण है?', a: ['कर्मचारी फिसला', 'गार्ड गायब था', 'औजार हाथ से लगा', 'निरीक्षण प्रणाली बार-बार गायब गार्ड पहचान और सुधार नहीं सकी'], correct: 3 },
      { q: 'कौन-सी सुधार योजना सबसे मजबूत है?', a: ['याद दिलाकर मामला तुरंत बंद करें', 'जहाँ संभव हो खतरा हटाएँ या engineering control दें, जिम्मेदार और तिथि तय करें, फिर प्रभावशीलता जाँचें', 'हर खतरे में केवल PPE', 'नियंत्रण से पहले काम खोलें'], correct: 1 },
    ],
  },
  bn: {
    slides: [
      { n: '01', title: 'ঘটনা ও অল্পের জন্য রক্ষা পাওয়া ঘটনা দ্রুত রিপোর্ট করুন', text: 'ঘটনা হলো এমন অনির্ধারিত ঘটনা যা আঘাত, অসুস্থতা, সম্পত্তি বা পরিবেশের ক্ষতি করেছে বা করতে পারত। প্রথমে জরুরি সহায়তা নিন, তারপর দেরি না করে সুপারভাইজার ও প্রকল্প HSE দলকে জানান। রিপোর্টিং সহজ, সঠিক ও প্রতিশোধমুক্ত হতে হবে।', ref: '29 CFR 1904.35; OSHA Incident Investigation' },
      { n: '02', title: 'স্থান নিরাপদ করুন ও প্রমাণ সংরক্ষণ করুন', text: 'তদন্তের আগে উদ্ধার ও চিকিৎসা সাড়া সম্পন্ন করুন। কাজ বন্ধ করুন, তাৎক্ষণিক বিপদ নিয়ন্ত্রণ করুন, শুধু প্রশিক্ষিত ও অনুমোদিত হলে বিপজ্জনক শক্তি বিচ্ছিন্ন করুন এবং এলাকা ব্যারিকেড করুন। কাউকে উদ্ধার বা আরও ক্ষতি রোধ ছাড়া সরঞ্জাম বা প্রমাণ সরাবেন না।', ref: 'OSHA Incident Investigation: A Guide for Employers, Steps 1–2' },
      { n: '03', title: 'প্রশিক্ষিত ও ভারসাম্যপূর্ণ তদন্ত দল গঠন করুন', text: 'একজন দায়িত্বশীল নেতা নির্ধারণ করুন এবং কাজ বোঝেন এমন ব্যবস্থাপক ও কর্মী অন্তর্ভুক্ত করুন। প্রয়োজনে HSE, কারিগরি বা বিশেষজ্ঞ সহায়তা নিন। কে তদন্ত করবে, কী তথ্য লাগবে, কে ব্যবস্থা অনুমোদন করবে এবং প্রতিটি কাজের সময়সীমা ঠিক করুন।', ref: 'OSHA Incident Investigation Overview; OSHA Recommended Practices' },
      { n: '04', title: 'সিদ্ধান্তের আগে তথ্য সংগ্রহ করুন', text: 'তারিখ, সময়, স্থান ও অবস্থা লিখুন। ছবি ও স্কেচ নিন, অবস্থান ও মাপ নথিবদ্ধ করুন, প্রাসঙ্গিক সরঞ্জাম সংরক্ষণ করুন এবং permit, Risk Assessment, পদ্ধতি, প্রশিক্ষণ, পরিদর্শন, maintenance, SDS ও পরিবেশগত তথ্য পর্যালোচনা করুন। যাচাইকৃত তথ্যকে অনুমান থেকে আলাদা রাখুন।', ref: 'OSHA Incident Investigation: A Guide for Employers, Appendices B–E' },
      { n: '05', title: 'দোষারোপ ছাড়া সাক্ষাৎকার নিন', text: 'সংশ্লিষ্ট ব্যক্তি ও সাক্ষীদের দ্রুত, আলাদাভাবে এবং উপযুক্ত স্থানে সাক্ষাৎকার নিন। বলুন লক্ষ্য প্রতিরোধ, “তারপর কী ঘটেছিল?” ধরনের উন্মুক্ত প্রশ্ন করুন, বাধা না দিয়ে শুনুন, বক্তব্য নিশ্চিত করুন এবং প্রয়োজনে দক্ষ দোভাষী দিন। ভয় দেখাবেন না বা উত্তর বলে দেবেন না।', ref: 'OSHA Incident Investigation: A Guide for Employers, Collect Information' },
      { n: '06', title: 'প্রত্যক্ষ, সহায়ক ও মূল কারণ খুঁজুন', text: 'শুধু “কর্মীর ভুল” বলে থামবেন না। সরঞ্জাম, উপকরণ, পরিবেশ, পদ্ধতি, তত্ত্বাবধান, কাজের চাপ, প্রশিক্ষণ, maintenance ও ব্যবস্থাপনা-ব্যবস্থার দুর্বলতা দেখুন। প্রমাণসহ 5 Whys বা cause-and-effect diagram ব্যবহার করুন, তারপর কারণগুলো ঘটনা ব্যাখ্যা করে কি না যাচাই করুন।', ref: 'OSHA Incident Investigation Overview; OSHA 3895' },
      { n: '07', title: 'আগে শক্তিশালী সংশোধনী ব্যবস্থা বেছে নিন', text: 'প্রতিটি নিশ্চিত কারণ নিয়ন্ত্রণের hierarchy অনুযায়ী সামলান: বিপদ দূর করুন, নিরাপদ বিকল্প দিন, engineering controls, তারপর administrative/work-practice controls এবং PPE। দায়িত্বশীল ব্যক্তি, অগ্রাধিকার ও সময়সীমা দিন; স্থায়ী সমাধান না হওয়া পর্যন্ত কার্যকর অস্থায়ী নিয়ন্ত্রণ রাখুন।', ref: 'OSHA Recommended Practices: Hazard Prevention and Control' },
      { n: '08', title: 'ঘটনা রিপোর্টিং সম্পন্ন করুন এবং সমাপ্তি যাচাই করুন', text: 'প্রতিটি ঘটনা ও অল্পের জন্য রক্ষা পাওয়া ঘটনা project incident-reporting প্রক্রিয়ায় দ্রুত রিপোর্ট করুন। supervisor ও project HSE team-কে জানান এবং গুরুতর ঘটনা TDC, client, project ও প্রযোজ্য সৌদি প্রয়োজনীয়তা অনুযায়ী অবিলম্বে escalate করুন। তথ্য, কারণ, ব্যবস্থা, দায়িত্ব ও সময়সীমা লিখুন, গুরুত্বপূর্ণ শিক্ষা ভাগ করুন এবং বন্ধ করার আগে সংশোধনী ব্যবস্থার কার্যকারিতা যাচাই করুন।', ref: 'TDC, client ও project incident-reporting পদ্ধতি; প্রযোজ্য সৌদি প্রয়োজনীয়তা' },
    ],
    quiz: [
      { q: 'ঘটনার পর সঠিক প্রথম পদক্ষেপ কী?', a: ['সঙ্গে সঙ্গে সাক্ষীর সাক্ষাৎকার শুরু করা', 'জরুরি সেবা দেওয়া, তাৎক্ষণিক বিপদ নিয়ন্ত্রণ করা এবং ঘটনা রিপোর্ট করা', 'সব সরঞ্জাম সরিয়ে ফেলা', 'কে দোষী তা ঠিক করা'], correct: 1 },
      { q: 'ঘটনা বা অল্পের জন্য রক্ষা পাওয়া ঘটনা রিপোর্ট করার সঠিক উপায় কী?', a: ['শুধু কেউ আহত হলে রিপোর্ট করা', 'পরবর্তী সাপ্তাহিক সভা পর্যন্ত অপেক্ষা করা', 'দ্রুত supervisor ও project HSE team-কে রিপোর্ট করা, তারপর TDC, client, project ও প্রযোজ্য সৌদি প্রয়োজনীয়তা অনুসরণ করা', 'তদন্ত শেষ হওয়া পর্যন্ত অপেক্ষা করা'], correct: 2 },
      { q: 'নির্ভরযোগ্য সাক্ষাৎকারের সেরা পদ্ধতি কোনটি?', a: ['আলাদাভাবে সাক্ষাৎকার, উন্মুক্ত প্রশ্ন এবং দোষারোপ এড়ানো', 'সবাইকে একসঙ্গে নিয়ে সম্মতি নেওয়া', 'প্রত্যাশিত উত্তর বলে দেওয়া', 'সংশোধনী কাজ শেষ হওয়া পর্যন্ত অপেক্ষা করা'], correct: 0 },
      { q: 'কোন ফলাফলটি শুধু তাৎক্ষণিক নয়, মূল কারণ?', a: ['কর্মী পিছলে গেছে', 'গার্ড ছিল না', 'সরঞ্জাম হাতে লেগেছে', 'পরিদর্শন ব্যবস্থা বারবার অনুপস্থিত গার্ড শনাক্ত ও সংশোধন করতে ব্যর্থ হয়েছে'], correct: 3 },
      { q: 'কোন সংশোধনী পরিকল্পনা সবচেয়ে শক্তিশালী?', a: ['মনে করিয়ে দিয়ে সঙ্গে সঙ্গে বন্ধ করা', 'যেখানে সম্ভব বিপদ দূর বা engineering control করা, দায়িত্ব ও সময়সীমা দেওয়া, তারপর কার্যকারিতা যাচাই করা', 'সব বিপদে শুধু PPE', 'নিয়ন্ত্রণের আগে কাজ চালু করা'], correct: 1 },
    ],
  },
};
