import type { CourseLanguage, CourseLesson } from './course-catalog';

export const scaffoldCourse: Record<CourseLanguage, CourseLesson> = {
  en: {
    slides: [
      { n: '01', title: 'Know who may design, inspect and change a scaffold', text: 'A qualified person designs the scaffold. It must support its own weight plus at least 4 times the maximum intended load. A competent person inspects visible defects before every work shift and after any event that could affect integrity. Only experienced, trained workers selected by a competent person may erect, move, dismantle or alter it under that person’s supervision. Stop work if the inspection tag is missing, the load is unknown or any component is bent, cracked, corroded or modified.', ref: '29 CFR 1926.451(a)(1), (a)(6), (f)(3), (f)(7)' },
      { n: '02', title: 'Build on a firm base and control the 4-to-1 ratio', text: 'Legs, posts, frames and uprights must sit on base plates and mud sills or another firm, level, rigid foundation—never loose blocks, bricks, barrels or other unstable objects. Keep uprights plumb and braced. When height exceeds 4 times the minimum base width, restrain the scaffold by ties, guys or braces. Place the first restraint near the 4:1 height, repeat vertically at no more than 20 ft for scaffolds 3 ft wide or less, or 26 ft when wider, and no more than 30 ft horizontally.', ref: '29 CFR 1926.451(c)(1)–(3)' },
      { n: '03', title: 'Fully plank the platform and remember 1–18–14', text: 'Working levels must be fully planked. Normal gaps between platform units or uprights may not exceed 1 in (2.5 cm). Platforms and walkways are normally at least 18 in (46 cm) wide. The front edge must normally be within 14 in (36 cm) of the work face unless guardrails or personal fall arrest are used. Planks extend at least 6 in over supports; maximum unsecured overhang is 12 in for planks 10 ft or shorter and 18 in for longer planks. Overlaps must be at least 12 in and occur over a support.', ref: '29 CFR 1926.451(b)(1)–(7)' },
      { n: '04', title: 'Use a real access system—never cross-braces', text: 'When a platform is more than 2 ft (0.6 m) above or below the access point, use a ladder, stair tower, ramp, walkway, integral access or similar safe means. Never climb cross-braces. The bottom rung of hook-on or attachable ladders may be no more than 24 in (61 cm) above the supporting level. Direct access from another surface is permitted only when the gap is no more than 14 in horizontally and 24 in vertically. Keep three-point contact and do not carry loads that prevent safe climbing.', ref: '29 CFR 1926.451(e)(1)–(8)' },
      { n: '05', title: 'Protect every worker above 10 feet', text: 'Each employee more than 10 ft (3.1 m) above a lower level needs the protection specified for that scaffold type. Most supported scaffolds use a compliant guardrail or personal fall-arrest system. A single-point or two-point adjustable suspension scaffold requires both guardrails and personal fall arrest. Scaffold toprails are generally 38–45 in (0.97–1.2 m) high and must resist at least 200 lb (890 N). Never attach a fall-arrest lifeline to the same suspension system that supports the platform.', ref: '29 CFR 1926.451(g)(1), (g)(3)–(4)' },
      { n: '06', title: 'Keep clear of electricity, wind, ice and overload', text: 'Do not exceed the rated capacity or maximum intended load. Maintain at least 3 ft (0.9 m) from insulated lines below 300 V and normally 10 ft (3.1 m) from insulated 300 V–50 kV lines or uninsulated lines below 50 kV. Work during storms or high winds is prohibited unless a competent person decides it is safe and workers use personal fall arrest or approved wind screens. Do not work on snow-, ice- or slip-covered platforms except to remove the hazard.', ref: '29 CFR 1926.451(f)(1), (f)(6), (f)(8), (f)(12)' },
      { n: '07', title: 'Prevent falling objects and unsafe shortcuts', text: 'Wear head protection and protect people below with toeboards, screens, debris nets, canopies or barricaded exclusion zones as required. Remove platform debris; do not use boxes, barrels or makeshift devices to gain height. Control swinging loads with tag lines when they could strike the scaffold. Do not move a scaffold with workers aboard unless the applicable engineered or mobile-scaffold requirements are satisfied. A competent person must remove damaged or weakened parts from service until repaired.', ref: '29 CFR 1926.451(f)(4)–(5), (f)(9), (f)(13)–(15), (h)' },
      { n: '08', title: 'Training must match the worker’s scaffold duties', text: 'A person qualified in scaffold hazards trains scaffold users on electrical, fall and falling-object hazards, correct protection, material handling, intended use and load limits. A competent person trains workers who erect, dismantle, move, repair, maintain or inspect scaffolds. Retrain after site, scaffold or protective-equipment changes, or whenever performance shows the worker has not retained the required skill. Memory rule: inspect, access, load, protect—before anyone climbs.', ref: '29 CFR 1926.454(a)–(c)' },
    ],
    quiz: [
      { q: 'A supported scaffold is 5 ft wide. At what height-to-base condition must it be restrained from tipping?', a: ['Only above 25 ft', 'When height is more than four times the minimum base width', 'Whenever two workers use it', 'Only during high winds'], correct: 1 },
      { q: 'Who must inspect a scaffold before each work shift and after an event that may affect integrity?', a: ['A competent person', 'Any worker wearing a harness', 'The client representative only', 'The equipment supplier'], correct: 0 },
      { q: 'Which platform condition normally complies with the basic dimensions?', a: ['12-in-wide platform with 3-in gaps', '18-in-wide platform located 24 in from the work face without protection', 'A plank extending only 2 in over its support', 'At least 18 in wide, gaps no more than 1 in, and front edge within 14 in unless fall protection is used'], correct: 3 },
      { q: 'What protection is required on a two-point adjustable suspension scaffold above 10 ft?', a: ['A warning line only', 'Both a guardrail system and personal fall arrest', 'A hard hat only', 'Personal fall arrest only'], correct: 1 },
      { q: 'When may cross-braces be climbed for scaffold access?', a: ['When the platform is below 10 ft', 'When approved by a coworker', 'Never; use an approved access system', 'Only while erecting the scaffold'], correct: 2 },
    ],
  },
  ar: {
    slides: [
      { n: '01', title: 'اعرف من يصمم ويفحص ويعدّل السقالة', text: 'يصمم السقالة شخص مؤهل، ويجب أن تتحمل وزنها إضافة إلى أربعة أمثال الحمل الأقصى المقصود على الأقل. يفحصها شخص مختص قبل كل وردية وبعد أي حدث قد يؤثر في سلامتها. لا ينصبها أو يحركها أو يفكها أو يعدلها إلا عمال مدربون وذوو خبرة يختارهم الشخص المختص وتحت إشرافه. أوقف العمل عند غياب الفحص أو جهل الحمل أو وجود جزء منحني أو متشقق أو متآكل أو معدل.', ref: '29 CFR 1926.451(a)(1), (a)(6), (f)(3), (f)(7)' },
      { n: '02', title: 'أساس ثابت ونسبة أربعة إلى واحد', text: 'توضع الأرجل والقوائم والإطارات على صفائح قواعد ومدادات طينية أو أساس ثابت ومستوي وصلب، وليس على طوب أو براميل أو أجسام غير مستقرة. تكون القوائم رأسية ومدعمة. إذا زاد الارتفاع على أربعة أمثال أقل عرض للقاعدة، تُثبت السقالة بروابط أو دعامات. يوضع أول تثبيت قرب ارتفاع 4:1، ثم كل 20 قدماً كحد أقصى إذا كان العرض 3 أقدام أو أقل، أو كل 26 قدماً إذا كان أوسع، وبمسافات أفقية لا تتجاوز 30 قدماً.', ref: '29 CFR 1926.451(c)(1)–(3)' },
      { n: '03', title: 'غطِّ المنصة بالكامل وتذكر 1–18–14', text: 'تُغطى مستويات العمل بالألواح بالكامل. لا تزيد الفجوات العادية على 1 بوصة (2.5 سم). عرض المنصة أو الممر 18 بوصة (46 سم) على الأقل عادة. لا تبعد الحافة الأمامية أكثر من 14 بوصة (36 سم) عن واجهة العمل إلا مع حواجز أو نظام إيقاف سقوط. يمتد اللوح 6 بوصات على الأقل فوق المسند؛ والامتداد غير المثبت 12 بوصة للوح بطول 10 أقدام أو أقل و18 بوصة للأطول. التراكب 12 بوصة على الأقل وفوق مسند.', ref: '29 CFR 1926.451(b)(1)–(7)' },
      { n: '04', title: 'استخدم وصولاً صحيحاً ولا تتسلق التدعيمات', text: 'إذا زادت المنصة على قدمين (0.6 م) فوق أو تحت نقطة الوصول، استخدم سلماً أو برج درج أو منحدراً أو ممراً أو وصولاً مدمجاً. لا تتسلق التدعيمات المتقاطعة. لا يزيد ارتفاع الدرجة السفلى للسلم المعلق على 24 بوصة (61 سم). يُسمح بالوصول المباشر من سطح آخر فقط إذا كانت الفجوة 14 بوصة أفقياً و24 بوصة رأسياً كحد أقصى. حافظ على ثلاث نقاط تلامس.', ref: '29 CFR 1926.451(e)(1)–(8)' },
      { n: '05', title: 'احمِ كل عامل فوق 10 أقدام', text: 'كل عامل على ارتفاع يزيد على 10 أقدام (3.1 م) فوق مستوى أدنى يحتاج حماية تناسب نوع السقالة. تستخدم أغلب السقالات المدعومة حواجز أو نظام إيقاف سقوط. السقالة المعلقة القابلة للضبط من نقطة أو نقطتين تتطلب الحواجز ونظام إيقاف السقوط معاً. ارتفاع الحاجز العلوي عادة 38–45 بوصة (0.97–1.2 م) ويتحمل 200 رطل (890 نيوتن) على الأقل. لا تربط خط الحياة بنظام التعليق نفسه الذي يحمل المنصة.', ref: '29 CFR 1926.451(g)(1), (g)(3)–(4)' },
      { n: '06', title: 'ابتعد عن الكهرباء والرياح والجليد والتحميل الزائد', text: 'لا تتجاوز السعة المقننة أو الحمل الأقصى المقصود. حافظ على 3 أقدام (0.9 م) من الخطوط المعزولة دون 300 فولت، و10 أقدام (3.1 م) عادة من الخطوط المعزولة 300 فولت–50 كيلوفولت أو غير المعزولة دون 50 كيلوفولت. يُمنع العمل أثناء العواصف أو الرياح الشديدة إلا إذا قرر شخص مختص أنه آمن مع الحماية المطلوبة. لا تعمل على سطح مغطى بالثلج أو الجليد إلا لإزالة الخطر.', ref: '29 CFR 1926.451(f)(1), (f)(6), (f)(8), (f)(12)' },
      { n: '07', title: 'امنع سقوط الأجسام والاختصارات الخطرة', text: 'ارتدِ خوذة واحمِ من هم أسفل السقالة بحواجز قدم أو شِباك أو مظلات أو منطقة عزل. أزل المخلفات ولا تستخدم صناديق أو براميل لزيادة الارتفاع. تحكم بالأحمال المتأرجحة بحبال توجيه. لا تحرك السقالة وعليها عمال إلا عند استيفاء متطلبات السقالة المتحركة أو التصميم الهندسي. يُخرج الشخص المختص الأجزاء التالفة من الخدمة حتى إصلاحها.', ref: '29 CFR 1926.451(f)(4)–(5), (f)(9), (f)(13)–(15), (h)' },
      { n: '08', title: 'التدريب حسب واجبات العامل', text: 'يدرّب شخص مؤهل مستخدمي السقالة على مخاطر الكهرباء والسقوط والأجسام الساقطة والحماية الصحيحة ومناولة المواد والاستخدام والأحمال. ويدرّب شخص مختص من ينصب أو يفك أو يحرك أو يصلح أو يفحص السقالة. أعد التدريب عند تغير الموقع أو السقالة أو معدات الحماية أو عند ظهور قصور في الأداء. قاعدة التذكر: افحص، اصعد بأمان، راقب الحمل، ثم احمِ.', ref: '29 CFR 1926.454(a)–(c)' },
    ],
    quiz: [
      { q: 'متى يجب تثبيت السقالة المدعومة ضد الانقلاب؟', a: ['فوق 25 قدماً فقط', 'عندما يزيد الارتفاع على أربعة أمثال أقل عرض للقاعدة', 'عند وجود عاملين', 'أثناء الرياح فقط'], correct: 1 },
      { q: 'من يفحص السقالة قبل كل وردية وبعد حدث قد يؤثر في سلامتها؟', a: ['شخص مختص', 'أي عامل بحزام', 'ممثل العميل فقط', 'المورد'], correct: 0 },
      { q: 'أي منصة توافق الأبعاد الأساسية عادة؟', a: ['عرض 12 بوصة وفجوات 3 بوصات', 'عرض 18 بوصة وبعد 24 بوصة بلا حماية', 'امتداد اللوح بوصتين فقط', 'عرض 18 بوصة، فجوات حتى بوصة، وبعد حتى 14 بوصة إلا مع الحماية'], correct: 3 },
      { q: 'ما الحماية اللازمة على سقالة معلقة قابلة للضبط من نقطتين فوق 10 أقدام؟', a: ['خط تحذير فقط', 'حواجز ونظام إيقاف سقوط معاً', 'خوذة فقط', 'نظام إيقاف سقوط فقط'], correct: 1 },
      { q: 'متى يجوز تسلق التدعيمات المتقاطعة؟', a: ['دون 10 أقدام', 'بموافقة زميل', 'لا يجوز أبداً؛ استخدم وصولاً معتمداً', 'أثناء التركيب فقط'], correct: 2 },
    ],
  },
  ur: {
    slides: [
      { n: '01', title: 'جانیں کون ڈیزائن، معائنہ اور تبدیلی کر سکتا ہے', text: 'اسکیفولڈ qualified person ڈیزائن کرے اور وہ اپنے وزن کے علاوہ زیادہ سے زیادہ مطلوبہ بوجھ کا کم از کم 4 گنا برداشت کرے۔ competent person ہر شفٹ سے پہلے اور سالمیت متاثر کرنے والے واقعے کے بعد ظاہری نقائص دیکھے۔ erection، حرکت، dismantling یا تبدیلی صرف اس کے منتخب تجربہ کار تربیت یافتہ کارکن اس کی نگرانی میں کریں۔ نامعلوم بوجھ، گم شدہ معائنہ یا مڑے، ٹوٹے، زنگ آلود یا تبدیل شدہ حصے پر کام روکیں۔', ref: '29 CFR 1926.451(a)(1), (a)(6), (f)(3), (f)(7)' },
      { n: '02', title: 'مضبوط بنیاد اور 4:1 تناسب', text: 'ٹانگیں اور فریم base plates اور mud sills یا مضبوط، ہموار بنیاد پر ہوں؛ اینٹ، ڈرم یا غیر مستحکم چیز پر نہیں۔ uprights سیدھے اور brace ہوں۔ اونچائی کم از کم base width کے 4 گنا سے بڑھے تو ties، guys یا braces لگائیں۔ پہلا tie تقریباً 4:1 پر، پھر 3 فٹ یا کم چوڑے اسکیفولڈ میں زیادہ سے زیادہ ہر 20 فٹ، زیادہ چوڑے میں ہر 26 فٹ، اور افقی طور پر ہر 30 فٹ سے زیادہ نہیں۔', ref: '29 CFR 1926.451(c)(1)–(3)' },
      { n: '03', title: 'پلیٹ فارم مکمل کریں—1، 18، 14 یاد رکھیں', text: 'کام کی سطح پوری plank ہو۔ عام خلا 1 انچ (2.5 سم) سے زیادہ نہیں۔ پلیٹ فارم عموماً کم از کم 18 انچ (46 سم) چوڑا ہو۔ سامنے کا کنارہ کام سے 14 انچ (36 سم) کے اندر ہو، ورنہ guardrail یا fall arrest لگائیں۔ plank support سے کم از کم 6 انچ آگے ہو؛ 10 فٹ یا چھوٹے plank کا غیر محفوظ overhang 12 انچ، لمبے کا 18 انچ۔ overlap کم از کم 12 انچ اور support پر ہو۔', ref: '29 CFR 1926.451(b)(1)–(7)' },
      { n: '04', title: 'صحیح رسائی استعمال کریں، cross-brace نہیں', text: 'پلیٹ فارم access point سے 2 فٹ (0.6 م) سے زیادہ اوپر یا نیچے ہو تو ladder، stair tower، ramp، walkway یا integral access استعمال کریں۔ cross-brace پر نہ چڑھیں۔ hook-on ladder کا نیچے والا rung support سے 24 انچ (61 سم) سے زیادہ اوپر نہ ہو۔ دوسرے surface سے direct access تبھی جب افقی gap 14 انچ اور عمودی 24 انچ سے زیادہ نہ ہو۔ تین نقاطِ رابطہ رکھیں۔', ref: '29 CFR 1926.451(e)(1)–(8)' },
      { n: '05', title: '10 فٹ سے اوپر ہر کارکن کو تحفظ دیں', text: 'نچلی سطح سے 10 فٹ (3.1 م) سے زیادہ اوپر ہر کارکن کو اسکیفولڈ کی قسم کے مطابق تحفظ چاہیے۔ عام supported scaffold پر guardrail یا personal fall arrest ہوتا ہے۔ single یا two-point adjustable suspension scaffold پر دونوں ضروری ہیں۔ toprail عموماً 38–45 انچ (0.97–1.2 م) اور کم از کم 200 lb (890 N) مضبوط ہو۔ lifeline کو پلیٹ فارم اٹھانے والے suspension system سے نہ باندھیں۔', ref: '29 CFR 1926.451(g)(1), (g)(3)–(4)' },
      { n: '06', title: 'بجلی، ہوا، برف اور overload سے بچیں', text: 'rated capacity یا maximum intended load سے تجاوز نہ کریں۔ 300 V سے کم insulated line سے 3 فٹ (0.9 م)، اور 300 V–50 kV insulated یا 50 kV سے کم uninsulated line سے عموماً 10 فٹ (3.1 م) دور رہیں۔ طوفان یا تیز ہوا میں کام ممنوع ہے جب تک competent person محفوظ قرار دے اور مطلوبہ تحفظ ہو۔ برف یا پھسلن والی سطح پر صرف خطرہ دور کرنے کے لیے جائیں۔', ref: '29 CFR 1926.451(f)(1), (f)(6), (f)(8), (f)(12)' },
      { n: '07', title: 'گرتی اشیاء اور خطرناک شارٹ کٹ روکیں', text: 'helmet پہنیں اور نیچے والوں کو toeboard، screen، net، canopy یا barricade سے بچائیں۔ debris ہٹائیں؛ اونچائی بڑھانے کے لیے box یا drum نہ رکھیں۔ swinging load کو tag line سے قابو کریں۔ کارکن موجود ہوں تو اسکیفولڈ نہ چلائیں جب تک mobile-scaffold یا engineered شرط پوری نہ ہو۔ competent person خراب حصہ مرمت تک سروس سے نکالے۔', ref: '29 CFR 1926.451(f)(4)–(5), (f)(9), (f)(13)–(15), (h)' },
      { n: '08', title: 'تربیت کام کی ذمہ داری کے مطابق ہو', text: 'qualified trainer صارفین کو بجلی، گرنے، گرتی اشیاء، صحیح protection، material handling، استعمال اور load limits سکھائے۔ competent person erection، dismantling، movement، repair، maintenance یا inspection کرنے والوں کو تربیت دے۔ site، scaffold یا protection بدلنے یا کمزور کارکردگی پر دوبارہ تربیت دیں۔ یاد رکھیں: معائنہ، محفوظ رسائی، بوجھ، تحفظ۔', ref: '29 CFR 1926.454(a)–(c)' },
    ],
    quiz: [
      { q: 'supported scaffold کو tipping سے کب restrain کرنا ہے؟', a: ['صرف 25 فٹ کے بعد', 'جب اونچائی کم از کم base width کے چار گنا سے زیادہ ہو', 'دو کارکن ہونے پر', 'صرف تیز ہوا میں'], correct: 1 },
      { q: 'ہر شفٹ سے پہلے معائنہ کون کرتا ہے؟', a: ['competent person', 'harness والا کوئی کارکن', 'صرف client', 'supplier'], correct: 0 },
      { q: 'کون سا بنیادی platform درست ہے؟', a: ['12 انچ چوڑا، 3 انچ gaps', '18 انچ چوڑا مگر 24 انچ دور بلا protection', 'support پر صرف 2 انچ', 'کم از کم 18 انچ، gaps 1 انچ تک، face سے 14 انچ تک ورنہ protection'], correct: 3 },
      { q: '10 فٹ سے اوپر two-point suspension scaffold پر کیا چاہیے؟', a: ['صرف warning line', 'guardrail اور personal fall arrest دونوں', 'صرف helmet', 'صرف fall arrest'], correct: 1 },
      { q: 'cross-brace کو access کے لیے کب چڑھ سکتے ہیں؟', a: ['10 فٹ سے کم', 'ساتھی کی اجازت سے', 'کبھی نہیں؛ منظور شدہ access استعمال کریں', 'صرف erection میں'], correct: 2 },
    ],
  },
  hi: {
    slides: [
      { n: '01', title: 'जानें कौन डिजाइन, निरीक्षण और बदलाव कर सकता है', text: 'योग्य व्यक्ति मचान डिजाइन करता है। मचान अपने वजन के साथ अधिकतम निर्धारित भार का कम-से-कम 4 गुना सह सके। सक्षम व्यक्ति हर शिफ्ट से पहले और संरचना प्रभावित करने वाली घटना के बाद दृश्य दोष जाँचे। उसी के चुने अनुभवी, प्रशिक्षित कर्मचारी उसकी निगरानी में मचान खड़ा, स्थानांतरित, खोल या बदल सकते हैं। भार अज्ञात हो, निरीक्षण न हुआ हो या भाग मुड़ा, टूटा, जंग लगा या बदला हो तो काम रोकें।', ref: '29 CFR 1926.451(a)(1), (a)(6), (f)(3), (f)(7)' },
      { n: '02', title: 'मजबूत आधार और 4:1 अनुपात', text: 'पैर और फ्रेम बेस प्लेट तथा मड सिल या मजबूत, समतल, कठोर आधार पर हों—ईंट, ड्रम या अस्थिर वस्तु पर नहीं। खंभे सीधे और ब्रेस किए हों। ऊँचाई न्यूनतम आधार चौड़ाई के 4 गुना से अधिक हो तो टाई/गाइ/ब्रेस लगाएँ। पहला बंधन लगभग 4:1 पर, फिर 3 ft या कम चौड़े मचान में अधिकतम हर 20 ft, अधिक चौड़े में हर 26 ft, और क्षैतिज दूरी अधिकतम 30 ft रखें।', ref: '29 CFR 1926.451(c)(1)–(3)' },
      { n: '03', title: 'प्लेटफॉर्म पूरा बिछाएँ—1, 18, 14 याद रखें', text: 'कार्य स्तर पूरी तरह प्लैंक हो। सामान्य खाली जगह 1 in (2.5 cm) से अधिक नहीं। प्लेटफॉर्म सामान्यतः कम-से-कम 18 in (46 cm) चौड़ा हो। सामने का किनारा कार्य-मुख से 14 in (36 cm) के भीतर हो, अन्यथा रेलिंग या फॉल अरेस्ट दें। प्लैंक सहारे से कम-से-कम 6 in आगे हो; 10 ft या छोटे प्लैंक का असुरक्षित ओवरहैंग 12 in और लंबे का 18 in। ओवरलैप कम-से-कम 12 in और सहारे के ऊपर हो।', ref: '29 CFR 1926.451(b)(1)–(7)' },
      { n: '04', title: 'सही पहुँच उपयोग करें—क्रॉस-ब्रेस नहीं', text: 'प्लेटफॉर्म पहुँच बिंदु से 2 ft (0.6 m) से अधिक ऊपर या नीचे हो तो सीढ़ी, स्टेयर टावर, रैम्प, वॉकवे या इंटीग्रल पहुँच दें। क्रॉस-ब्रेस पर न चढ़ें। हुक-ऑन सीढ़ी की निचली पायदान सहारे से 24 in (61 cm) से अधिक ऊपर न हो। दूसरे तल से सीधी पहुँच तभी जब क्षैतिज अंतर अधिकतम 14 in और ऊर्ध्व अंतर 24 in हो। तीन-बिंदु संपर्क रखें।', ref: '29 CFR 1926.451(e)(1)–(8)' },
      { n: '05', title: '10 फीट से ऊपर हर कर्मचारी को बचाएँ', text: 'निचले स्तर से 10 ft (3.1 m) से अधिक ऊपर प्रत्येक कर्मचारी को मचान प्रकार के अनुसार सुरक्षा चाहिए। सामान्य समर्थित मचान पर रेलिंग या व्यक्तिगत फॉल अरेस्ट होता है। एक या दो-बिंदु समायोज्य निलंबित मचान पर दोनों आवश्यक हैं। टॉपरेल सामान्यतः 38–45 in (0.97–1.2 m) ऊँची और कम-से-कम 200 lb (890 N) सहने वाली हो। लाइफलाइन को प्लेटफॉर्म उठाने वाले निलंबन से न बाँधें।', ref: '29 CFR 1926.451(g)(1), (g)(3)–(4)' },
      { n: '06', title: 'बिजली, हवा, बर्फ और अधिक भार से बचें', text: 'रेटेड क्षमता या अधिकतम निर्धारित भार न लाँघें। 300 V से कम इंसुलेटेड लाइन से 3 ft (0.9 m), और 300 V–50 kV इंसुलेटेड या 50 kV से कम अनइंसुलेटेड लाइन से सामान्यतः 10 ft (3.1 m) दूर रहें। तूफान या तेज हवा में काम तभी जब सक्षम व्यक्ति सुरक्षित माने और आवश्यक सुरक्षा हो। बर्फ या फिसलन वाले प्लेटफॉर्म पर खतरा हटाने के अलावा काम न करें।', ref: '29 CFR 1926.451(f)(1), (f)(6), (f)(8), (f)(12)' },
      { n: '07', title: 'गिरती वस्तुएँ और खतरनाक शॉर्टकट रोकें', text: 'सिर की सुरक्षा पहनें और नीचे लोगों को टोबोर्ड, स्क्रीन, नेट, कैनोपी या बैरिकेड से बचाएँ। मलबा हटाएँ; ऊँचाई बढ़ाने के लिए बॉक्स या ड्रम न रखें। झूलते भार को टैग लाइन से नियंत्रित करें। कर्मचारी सवार हों तो मचान न चलाएँ जब तक मोबाइल-मचान या इंजीनियर्ड शर्तें पूरी न हों। सक्षम व्यक्ति खराब भाग को मरम्मत तक सेवा से हटाए।', ref: '29 CFR 1926.451(f)(4)–(5), (f)(9), (f)(13)–(15), (h)' },
      { n: '08', title: 'प्रशिक्षण कार्य के अनुसार हो', text: 'विषय में योग्य व्यक्ति उपयोगकर्ताओं को विद्युत, गिरने, गिरती वस्तु, सही सुरक्षा, सामग्री संचालन, उपयोग और भार सीमा सिखाए। सक्षम व्यक्ति खड़ा करने, खोलने, चलाने, मरम्मत, रखरखाव या निरीक्षण करने वालों को प्रशिक्षित करे। स्थल, मचान या सुरक्षा बदलने अथवा खराब प्रदर्शन पर पुनः प्रशिक्षण दें। याद रखें: निरीक्षण, सुरक्षित पहुँच, भार, सुरक्षा।', ref: '29 CFR 1926.454(a)–(c)' },
    ],
    quiz: [
      { q: 'समर्थित मचान को पलटने से कब बाँधना आवश्यक है?', a: ['केवल 25 ft के बाद', 'ऊँचाई न्यूनतम आधार चौड़ाई के चार गुना से अधिक होने पर', 'दो कर्मचारी होने पर', 'केवल तेज हवा में'], correct: 1 },
      { q: 'हर शिफ्ट से पहले निरीक्षण कौन करता है?', a: ['सक्षम व्यक्ति', 'हार्नेस पहना कोई कर्मचारी', 'केवल ग्राहक', 'आपूर्तिकर्ता'], correct: 0 },
      { q: 'कौन-सा प्लेटफॉर्म सामान्य मूल आयाम पूरा करता है?', a: ['12 in चौड़ा, 3 in अंतर', '18 in चौड़ा पर 24 in दूर बिना सुरक्षा', 'सहारे से केवल 2 in आगे', 'कम-से-कम 18 in, अंतर अधिकतम 1 in, कार्य-मुख से 14 in तक या सुरक्षा'], correct: 3 },
      { q: '10 ft से ऊपर दो-बिंदु निलंबित मचान पर क्या चाहिए?', a: ['केवल चेतावनी रेखा', 'रेलिंग और व्यक्तिगत फॉल अरेस्ट दोनों', 'केवल हेलमेट', 'केवल फॉल अरेस्ट'], correct: 1 },
      { q: 'पहुँच के लिए क्रॉस-ब्रेस कब चढ़ सकते हैं?', a: ['10 ft से नीचे', 'सहकर्मी की अनुमति से', 'कभी नहीं; स्वीकृत पहुँच उपयोग करें', 'केवल खड़ा करते समय'], correct: 2 },
    ],
  },
};

